(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"Scene4_atlas_", frames: [[292,3299,58,58],[0,1026,1280,1024],[443,3078,250,250],[0,3078,441,219],[1282,0,282,1024],[0,0,1280,1024],[0,2052,1280,1024],[0,3299,230,95],[695,3078,230,95],[1282,1026,123,1024],[1282,2052,97,1024],[232,3299,58,58]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.Checkbox = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.GirlEur = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.Globe = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.GlobeEarth = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.Globeshadow = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.ManAus = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.ManUS = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.returnbuttonhover = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();



(lib.returnbutton = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(8);
}).prototype = p = new cjs.Sprite();



(lib.rightbtn = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(9);
}).prototype = p = new cjs.Sprite();



(lib.rightNav = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(10);
}).prototype = p = new cjs.Sprite();



(lib.unCheckbox = function() {
	this.spriteSheet = ss["Scene4_atlas_"];
	this.gotoAndStop(11);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.TextBoi = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgPAQQgIgGAAgKQAAgKAIgGQAGgHAJAAQALAAAGAHQAGAGABAKQAAAKgHAGQgGAIgLAAQgJAAgGgIg");
	this.shape.setTransform(1084.6,166.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUAAgZQAAgZAKgTQAJgTASgMQASgLAYgBQAOABAKACIAQAFIAGADIAAh8QgBgEADgCQACgCAEAAIAMAAQADAAADACQACACAAAEIAAEVQAAADgCACQgDADgDAAIgJAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgHAGQgGAFgMAFQgLAGgPAAQgVAAgSgMgAgWAJQgMAIgHANQgGAOAAARQAAAQAGAOQAHAOALAJQAKAIAPABQAMgBAIgEQAJgEAFgFIAJgKIADgEIAAhUIgGgDIgOgFQgJgCgMAAQgRAAgMAIg");
	this.shape_1.setTransform(1069.1,154.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_2.setTransform(1050.1,160.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgQBrQgJgFgCgLQgDgKAAgNIAAhkIgVAAQgEAAgCgDQgCgCAAgDIAAgJQAAgEACgCQACgDAEABIAVAAIAAgvQAAgDADgDQACgCADAAIANgBQAEAAACACQACADAAADIAAAwIAwAAQADgBACADQADACAAAEIAAAJQAAADgDACQgCADgDAAIgwAAIAABhQAAANACADQAEAFAHAAQAIgBAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEABIgLAGQgHAEgKACQgKADgKAAQgQAAgIgHg");
	this.shape_3.setTransform(1033.2,157.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgxBKQgPgPAAgaIAAAAQAAgZARgOQASgPAfgBQAJABAIABIAOADIAFABQABgXgGgMQgFgLgRABQgRgBgOAEIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgDgKQgBgEABgCQABgCADgCIAKgCQAIgDAMgDQANgCAPAAQAVgBAMAJQALAGAFAQQAEARAAAYIAABcQAAAEgCACQgDACgDAAIgIAAQgDAAgCgBIgCgFIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgOgAgaAJQgLAHAAARIAAAAQAAANAIAJQAIAIANAAQAPgBANgGQAMgIAFgJIAAghQgDgCgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_4.setTransform(1016.7,160.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgfBNQgUgMgMgTQgLgUgBgZQABgZAMgTQAMgVATgMQAUgLAWAAQATAAAPAHQAPAIALAOQACADAAADQgBAEgDACIgIAGQgEAFgDgCIgFgEQgGgIgKgEQgKgGgNAAQgOABgNAHQgNAIgHANQgHAOAAAQQAAARAHANQAHAOANAJQAMAHAPAAQASAAAKgHQAKgGAGgJQAEgDADAAQADAAADADIAFADQADACABAEQABADgCADQgKAQgQAJQgRAKgWABQgWgBgTgLg");
	this.shape_5.setTransform(999.2,160.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXAAQAYAAASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbgzQgMAHgHAOQgHANgBARQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgRgHgNQgHgOgMgHQgNgJgPAAQgPAAgMAJg");
	this.shape_6.setTransform(979.8,160.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgGCTQgDAAgCgCQgDgCAAgEIAAkVQAAgDADgCQACgDADAAIANAAQADAAACADQACACABADIAAEVQgBAEgCACQgCACgDAAg");
	this.shape_7.setTransform(965.2,154.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_8.setTransform(941.9,160.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_9.setTransform(926.5,160.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgxBKQgPgPAAgaIAAAAQAAgZARgOQASgPAfgBQAJABAIABIAOADIAFABQABgXgGgMQgFgLgRABQgRgBgOAEIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgDgKQgBgEABgCQABgCADgCIAKgCQAIgDAMgDQANgCAPAAQAVgBAMAJQALAGAFAQQAEARAAAYIAABcQAAAEgCACQgDACgDAAIgIAAQgDAAgCgBIgCgFIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgOgAgaAJQgLAHAAARIAAAAQAAANAIAJQAIAIANAAQAPgBANgGQAMgIAFgJIAAghQgDgCgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_10.setTransform(908.8,160.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("Ag7CTQgFgBgCgCQgCgDACgEIA2h0IhOieQgCgEABgCQACgDAFAAIATAAIAEACQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAABIA+CAIAAAAIA7iAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAQAAQAFAAACADQABACgCAEIiAEXIgDAEQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_11.setTransform(881.4,166.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_12.setTransform(862.1,160.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AA2CTQgEAAgCgCQgCgCAAgEIAAhZQgBgXgJgNQgKgLgSAAQgPAAgNAGQgLAGgIAFIgGAHIAABwQgBAEgCACQgCACgDAAIgNAAQgDAAgCgCQgDgCAAgEIAAkVQAAgDADgCQACgDADAAIANAAQADAAACADQACACABADIAACIIAGgGQAIgFAMgFQANgGAQAAQAfAAARATQARATAAAkIAABZQAAAEgCACQgCACgEAAg");
	this.shape_13.setTransform(842.2,154.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgQBrQgJgFgCgLQgDgKAAgNIAAhkIgVAAQgEAAgCgDQgCgCAAgDIAAgJQAAgEACgCQACgDAEABIAVAAIAAgvQAAgDADgDQACgCADAAIANgBQAEAAACACQACADAAADIAAAwIAwAAQADgBACADQADACAAAEIAAAJQAAADgDACQgCADgDAAIgwAAIAABhQAAANACADQAEAFAHAAQAIgBAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEABIgLAGQgHAEgKACQgKADgKAAQgQAAgIgHg");
	this.shape_14.setTransform(824.4,157.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_15.setTransform(798.4,160.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_16.setTransform(783,160.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_17.setTransform(765.2,160.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AA1CTQgCAAgDgCQgCgCAAgEIAAhZQAAgXgLgNQgJgLgSAAQgPAAgNAGQgLAGgIAFIgGAHIAABwQgBAEgCACQgCACgDAAIgNAAQgDAAgDgCQgCgCAAgEIAAkVQAAgDACgCQADgDADAAIANAAQADAAACADQACACABADIAACIIAGgGQAIgFAMgFQANgGAQAAQAfAAARATQARATAAAkIAABZQAAAEgCACQgDACgDAAg");
	this.shape_18.setTransform(745.2,154.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AA6BZQgDAAgCgCIgCgDIgzh9IgxB9IgCADQgCACgDAAIgCAAQgBAAAAgBQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIgvieQgBgEABgCQACgDAEAAIANAAQADAAACACQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAfBtIAAAAIAwhyIACgDIAEgBIACAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIADADIAvBzIAAAAIAfhuQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAABAAQAAAAABAAIANAAQAFAAABADQABACgBAEIguCeQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQAAABgBAAg");
	this.shape_19.setTransform(722,160.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_20.setTransform(689.7,160.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgxBKQgPgPAAgaIAAAAQAAgZARgOQASgPAfgBQAJABAIABIAOADIAFABQABgXgGgMQgFgLgRABQgRgBgOAEIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgDgKQgBgEABgCQABgCADgCIAKgCQAIgDAMgDQANgCAPAAQAVgBAMAJQALAGAFAQQAEARAAAYIAABcQAAAEgCACQgDACgDAAIgIAAQgDAAgCgBIgCgFIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgOgAgaAJQgLAHAAARIAAAAQAAANAIAJQAIAIANAAQAPgBANgGQAMgIAFgJIAAghQgDgCgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_21.setTransform(669.8,160.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AA2CTQgEAAgCgCQgCgCAAgEIAAhZQgBgXgJgNQgKgLgSAAQgPAAgNAGQgMAGgHAFIgGAHIAABwQgBAEgCACQgCACgDAAIgNAAQgEAAgBgCQgDgCAAgEIAAkVQAAgDADgCQABgDAEAAIANAAQADAAACADQACACABADIAACIIAGgGQAIgFAMgFQANgGAQAAQAgAAAQATQARATAAAkIAABZQAAAEgCACQgDACgDAAg");
	this.shape_22.setTransform(651.3,154.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgQBrQgJgFgCgLQgDgKAAgNIAAhkIgVAAQgEAAgCgDQgCgCAAgDIAAgJQAAgEACgCQACgDAEABIAVAAIAAgvQAAgDADgDQACgCADAAIANgBQAEAAACACQACADAAADIAAAwIAwAAQADgBACADQADACAAAEIAAAJQAAADgDACQgCADgDAAIgwAAIAABhQAAANACADQAEAFAHAAQAIgBAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEABIgLAGQgHAEgKACQgKADgKAAQgQAAgIgHg");
	this.shape_23.setTransform(633.5,157.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_24.setTransform(611.3,160.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_25.setTransform(593.5,160.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AA2CTQgEAAgCgCQgCgCAAgEIAAhZQgBgXgJgNQgKgLgSAAQgPAAgNAGQgLAGgIAFIgGAHIAABwQgBAEgCACQgCACgDAAIgNAAQgEAAgBgCQgDgCAAgEIAAkVQAAgDADgCQABgDAEAAIANAAQADAAACADQACACABADIAACIIAGgGQAIgFAMgFQANgGAQAAQAfAAARATQARATAAAkIAABZQAAAEgCACQgCACgEAAg");
	this.shape_26.setTransform(573.5,154.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgQBrQgJgFgCgLQgDgKAAgNIAAhkIgVAAQgEAAgCgDQgCgCAAgDIAAgJQAAgEACgCQACgDAEABIAVAAIAAgvQAAgDADgDQACgCADAAIANgBQAEAAACACQACADAAADIAAAwIAwAAQADgBACADQADACAAAEIAAAJQAAADgDACQgCADgDAAIgwAAIAABhQAAANACADQAEAFAHAAQAIgBAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEABIgLAGQgHAEgKACQgKADgKAAQgQAAgIgHg");
	this.shape_27.setTransform(555.8,157.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgxBKQgPgPAAgaIAAAAQAAgZARgOQASgPAfgBQAJABAIABIAOADIAFABQABgXgGgMQgFgLgRABQgRgBgOAEIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgDgKQgBgEABgCQABgCADgCIAKgCQAIgDAMgDQANgCAPAAQAVgBAMAJQALAGAFAQQAEARAAAYIAABcQAAAEgCACQgDACgDAAIgIAAQgDAAgCgBIgCgFIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgOgAgaAJQgLAHAAARIAAAAQAAANAIAJQAIAIANAAQAPgBANgGQAMgIAFgJIAAghQgDgCgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_28.setTransform(539.2,160.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_29.setTransform(525.2,160.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgGCTQgDAAgCgCQgDgCAAgEIAAkVQAAgDADgCQACgDADAAIANAAQADAAACADQACACABADIAAEVQgBAEgCACQgCACgDAAg");
	this.shape_30.setTransform(503.2,154.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgFCTQgEAAgCgCQgCgCAAgEIAAkVQAAgDACgCQACgDAEAAIALAAQAEAAACADQACACAAADIAAEVQAAAEgCACQgCACgEAAg");
	this.shape_31.setTransform(494.2,154.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgFCPQgDAAgCgDQgDgCAAgDIAAiXQAAgDADgDQACgCADAAIAMAAQADAAADACQABADABADIAACXQgBADgBACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAFgGAIAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_32.setTransform(485.3,154.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AAvCTIgFgBIgEgCIhUhRIAABMQAAAEgCACQgDACgDAAIgNAAQgDAAgCgCQgDgCAAgEIAAkVQAAgDADgCQACgDADAAIANAAQADAAADADQACACAAADIAAC1IBGg6IAGgDQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAXAAQAFABABAEQAAADgCADIhPA/IBcBTQACACAAAEQgBADgFABg");
	this.shape_33.setTransform(472.7,154.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgiBSQgNgHgHgGIgCgEIAAgFIADgFIADgFQACgDADAAQADgBADACIAGAFIAOAGQAJAFAKAAQANgBAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgKALgIQAMgHATAAQAQAAAMAEQAMAEAGAEQADACABAEQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgDgHAAQgOABgFAFQgFAFAAAGQABAKAIAHQAJAFANAHIAbAOQAMAHAIAJQAIALAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_34.setTransform(454.8,160.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_35.setTransform(427.5,160.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXAAQAYAAASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbgzQgMAHgHAOQgHANgBARQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgRgHgNQgHgOgMgHQgNgJgPAAQgPAAgMAJg");
	this.shape_36.setTransform(406.9,160.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_37.setTransform(377.2,160.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXAAQAYAAASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbgzQgMAHgHAOQgHANgBARQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgRgHgNQgHgOgMgHQgNgJgPAAQgPAAgMAJg");
	this.shape_38.setTransform(356.5,160.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgFCPQgDAAgCgDQgDgCAAgDIAAiXQAAgDADgDQACgCADAAIAMAAQADAAACACQACADABADIAACXQgBADgCACQgCADgDAAgAgOhsQgFgFAAgJQAAgIAFgGQAHgGAHAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgHAAgHgGg");
	this.shape_39.setTransform(342,154.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgiBSQgNgHgHgGIgCgEIAAgFIADgFIADgFQACgDADAAQADgBADACIAGAFIAOAGQAJAFAKAAQANgBAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgKALgIQAMgHATAAQAQAAAMAEQAMAEAGAEQADACABAEQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgDgHAAQgOABgFAFQgFAFAAAGQABAKAIAHQAJAFANAHIAbAOQAMAHAIAJQAIALAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_40.setTransform(330.3,160.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgFCPQgEAAgCgDQgCgCAAgDIAAiXQAAgDACgDQACgCAEAAIAMAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAFgGAIAAQAIAAAGAGQAGAGAAAIQAAAJgGAFQgGAGgIAAQgIAAgFgGg");
	this.shape_41.setTransform(318.2,154.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgfBNQgUgMgMgTQgLgUgBgZQABgZAMgTQAMgVATgMQAUgLAWAAQATAAAPAHQAPAIALAOQACADAAADQgBAEgDACIgIAGQgEAFgDgCIgFgEQgGgIgKgEQgKgGgNAAQgOABgNAHQgNAIgHANQgHAOAAAQQAAARAHANQAHAOANAJQAMAHAPAAQASAAAKgHQAKgGAGgJQAEgDADAAQADAAADADIAFADQADACABAEQABADgCADQgKAQgQAJQgRAKgWABQgWgBgTgLg");
	this.shape_42.setTransform(304.5,160.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_43.setTransform(285.7,160.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUAAgZQAAgZAKgTQAJgTASgMQASgLAYgBQAOABAKACIAQAFIAGADIAAh8QAAgEACgCQACgCAEAAIAMAAQADAAADACQACACABAEIAAEVQgBADgCACQgDADgDAAIgIAAQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgHAGQgGAFgMAFQgLAGgPAAQgVAAgSgMgAgWAJQgMAIgHANQgGAOAAARQAAAQAGAOQAHAOALAJQAKAIAPABQAMgBAIgEQAJgEAFgFIAJgKIADgEIAAhUIgGgDIgOgFQgJgCgMAAQgRAAgMAIg");
	this.shape_44.setTransform(265.3,154.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYAAQAWAAARAKQASAKAJARQAKASAAAVIAAAGIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygPQgBgNgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAVIBjAAIAAAAg");
	this.shape_45.setTransform(237,160.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AA2CTQgDAAgDgCQgCgCAAgEIAAhZQgBgXgJgNQgKgLgSAAQgPAAgNAGQgMAGgHAFIgGAHIAABwQgBAEgCACQgCACgDAAIgNAAQgEAAgBgCQgDgCAAgEIAAkVQAAgDADgCQABgDAEAAIANAAQADAAACADQACACABADIAACIIAGgGQAIgFAMgFQANgGAQAAQAgAAAQATQARATAAAkIAABZQAAAEgCACQgCACgEAAg");
	this.shape_46.setTransform(217,154.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgQBrQgJgFgCgLQgDgKAAgNIAAhkIgVAAQgEAAgCgDQgCgCAAgDIAAgJQAAgEACgCQACgDAEABIAVAAIAAgvQAAgDADgDQACgCADAAIANgBQAEAAACACQACADAAADIAAAwIAwAAQADgBACADQADACAAAEIAAAJQAAADgDACQgCADgDAAIgwAAIAABhQAAANACADQAEAFAHAAQAIgBAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEABIgLAGQgHAEgKACQgKADgKAAQgQAAgIgHg");
	this.shape_47.setTransform(199.3,157.9);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAADgEADQgIAHgQAGQgQAGgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPAMQgOAOgDATIBjAAIAAAAg");
	this.shape_48.setTransform(1106.8,122.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgiBSQgNgHgHgFIgCgFIAAgEIADgGIADgFQACgCADgBQADAAADABIAGAFIAOAHQAJAEAKgBQANAAAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgLALgHQAMgHATgBQAQABAMAEQAMAEAGAFQADACABADQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgCgHgBQgOABgFAFQgFAGAAAFQABAKAIAHQAJAGANAFIAbAPQAMAHAIAKQAIAKAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_49.setTransform(1089.8,122.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfgBQAJAAAIACIAOADIAFABQABgXgGgMQgFgLgRAAQgRABgOADIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgCAMgDQANgCAPgBQAVAAAMAIQALAHAFARQAEAQAAAYIAABcQAAADgCADQgDACgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAHAAARIAAABQAAAMAIAJQAIAIANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_50.setTransform(1072.8,122.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgaCPQgLgFgHgGIgGgFIgDALQAAADgCACQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgIAAQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIANAAQADAAACACQACACABAEIAAB8IAFgDIAPgFQAKgCAOgBQAZABASALQASAMAJATQAKATAAAZQAAAZgKAUQgKAUgSAMQgRAMgVAAQgPAAgMgGgAgbADIgPAFIgFADIAABUIADAEIAIAKQAGAFAJAEQAIAEAMABQAOgBALgIQALgJAHgOQAGgOAAgQQAAgRgGgOQgHgNgMgIQgMgIgRAAQgMAAgJACg");
	this.shape_51.setTransform(1055,116.3);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUAAgZQAAgZAKgTQAJgTASgMQASgLAYgBQAOABAKACIAQAFIAGADIAAh8QgBgEADgCQACgCAEAAIAMAAQADAAADACQACACAAAEIAAEVQAAADgCACQgDADgDAAIgJAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgHAGQgGAFgMAFQgLAGgPAAQgWAAgRgMgAgWAJQgMAIgHANQgGAOAAARQAAAQAGAOQAHAOALAJQALAIAOABQAMgBAIgEQAIgEAHgFIAIgKIADgEIAAhUIgGgDIgOgFQgJgCgMAAQgRAAgMAIg");
	this.shape_52.setTransform(1024.2,116.3);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_53.setTransform(1004.4,122.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfgBQAJAAAIACIAOADIAFABQABgXgGgMQgFgLgRAAQgRABgOADIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgCAMgDQANgCAPgBQAVAAAMAIQALAHAFARQAEAQAAAYIAABcQAAADgCADQgDACgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAHAAARIAAABQAAAMAIAJQAIAIANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_54.setTransform(984.5,122.4);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgSB6IgGgGQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAgDADgCIAJgJQAGgHAGgKQAEgMAAgPIgCABIgBAAQgKgBgHgHQgHgGAAgLQAAgKAHgHQAHgGAKgBQAJAAAIAIQAJAIAAAXQAAARgGAPQgGAPgIAMQgHALgHAHQgDADgDAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBgBAAAAgAgRhRQgHgHAAgKQAAgLAHgGQAHgHAKgBQAJABAHAHQAGAGABALQgBAKgGAHQgHAGgJAAQgKAAgHgGg");
	this.shape_55.setTransform(961.5,125.9);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgaCPQgLgFgHgGIgGgFIgDALQAAADgCACQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgIAAQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIANAAQADAAACACQACACABAEIAAB8IAFgDIAPgFQAKgCAOgBQAZABASALQASAMAJATQAKATAAAZQAAAZgKAUQgKAUgSAMQgRAMgVAAQgPAAgMgGgAgbADIgPAFIgFADIAABUIADAEIAIAKQAGAFAJAEQAIAEAMABQAOgBALgIQALgJAHgOQAGgOAAgQQAAgRgGgOQgHgNgMgIQgMgIgRAAQgMAAgJACg");
	this.shape_56.setTransform(946.6,116.3);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_57.setTransform(925.7,122.4);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AgnDKQgLgGgGgFQgCgCAAgDQgBgDACgCIAGgLQACgDADAAQADAAADADQAFADAJAEQAJAFAIAAQAOAAAJgLQAKgKABgYIAAjaQAAgEACgCQACgCAEAAIANAAQADAAACACQACACABAEIAADaQgBAYgIAQQgJAQgOAHQgOAIgSAAQgRAAgMgGgAAZitQgGgFAAgJQAAgIAGgGQAFgGAJAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgJAAgFgGg");
	this.shape_58.setTransform(907.2,123);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAADgEADQgIAHgQAGQgQAGgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPAMQgOAOgDATIBjAAIAAAAg");
	this.shape_59.setTransform(887.8,122.4);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AA2CTQgEAAgCgCQgCgDAAgDIAAhYQgBgZgJgLQgKgMgSAAQgPAAgNAGQgLAGgIAFIgGAHIAABwQgBADgCADQgCACgDAAIgNAAQgEAAgBgCQgDgDAAgDIAAkVQAAgDADgCQABgDAEAAIANAAQADAAACADQACACABADIAACIIAGgGQAIgFAMgFQANgGAQgBQAfABARATQARASAAAmIAABYQAAADgCADQgCACgEAAg");
	this.shape_60.setTransform(867.8,116.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEgBgCgBQgCgDAAgDIAAgJQAAgEACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAAEIAAAJQAAADgDADQgCABgDABIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQAAgIgGg");
	this.shape_61.setTransform(850.1,119.8);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_62.setTransform(827.9,122.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_63.setTransform(809.4,122.4);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AgeCVQgEAAgDgCQgBgCAAgEIAAiGIgbAAQgDgBgCgCQgCgCgBgCIAAgKQABgDACgCQACgDADAAIAbAAIAAg7QAAgYAIgQQAJgQAOgHQANgIASAAQASAAALAGQAMAFAFAGQADACABADIgCAFIgGALQgDADgCAAQgDAAgEgDQgEgDgIgFQgJgEgJAAQgPAAgJALQgJAKgBAYIAAA7IAwAAQADAAACADQADACAAADIAAAKQAAACgDACQgCACgDABIgwAAIAACGQAAAEgCACQgCACgEAAg");
	this.shape_64.setTransform(794.2,115.8);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgiBSQgNgHgHgFIgCgFIAAgEIADgGIADgFQACgCADgBQADAAADABIAGAFIAOAHQAJAEAKgBQANAAAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgLALgHQAMgHATgBQAQABAMAEQAMAEAGAFQADACABADQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgCgHgBQgOABgFAFQgFAGAAAFQABAKAIAHQAJAGANAFIAbAPQAMAHAIAKQAIAKAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_65.setTransform(769.3,122.4);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAADgEADQgIAHgQAGQgQAGgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPAMQgOAOgDATIBjAAIAAAAg");
	this.shape_66.setTransform(752.1,122.4);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEgBgCgBQgCgDAAgDIAAgJQAAgEACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAAEIAAAJQAAADgDADQgCABgDABIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQAAgIgGg");
	this.shape_67.setTransform(735.2,119.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfgBQAJAAAIACIAOADIAFABQABgXgGgMQgFgLgRAAQgRABgOADIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgCAMgDQANgCAPgBQAVAAAMAIQALAHAFARQAEAQAAAYIAABcQAAADgCADQgDACgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAHAAARIAAABQAAAMAIAJQAIAIANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_68.setTransform(718.7,122.4);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUAAgZQAAgZAKgTQAJgTASgMQASgLAYgBQAOABAKACIAQAFIAGADIAAh8QgBgEADgCQACgCAEAAIAMAAQADAAADACQACACAAAEIAAEVQAAADgCACQgDADgDAAIgJAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgHAGQgGAFgMAFQgLAGgPAAQgVAAgSgMgAgWAJQgMAIgHANQgGAOAAARQAAAQAGAOQAHAOALAJQAKAIAPABQAMgBAIgEQAJgEAFgFIAJgKIADgEIAAhUIgGgDIgOgFQgJgCgMAAQgRAAgMAIg");
	this.shape_69.setTransform(699.7,116.3);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AgFCPQgEAAgCgDQgCgCAAgDIAAiXQAAgDACgDQACgCAEAAIAMAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAGgGAHAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgHAAgGgGg");
	this.shape_70.setTransform(685.7,116.5);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUgBgZQABgZAKgTQAJgTASgMQASgLAYgBQAOABAKACIAQAFIAFADIAAh8QAAgEADgCQACgCADAAIAOAAQADAAACACQACACABAEIAAEVQgBADgCACQgCADgDAAIgJAAQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgGAGQgHAFgLAFQgMAGgPAAQgWAAgRgMgAgXAJQgLAIgHANQgGAOAAARQAAAQAGAOQAGAOALAJQAMAIAOABQALgBAJgEQAJgEAFgFIAJgKIADgEIAAhUIgFgDIgPgFQgJgCgMAAQgRAAgNAIg");
	this.shape_71.setTransform(670.6,116.3);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_72.setTransform(650.8,122.1);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfgBQAJAAAIACIAOADIAFABQABgXgGgMQgFgLgRAAQgRABgOADIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgCAMgDQANgCAPgBQAVAAAMAIQALAHAFARQAEAQAAAYIAABcQAAADgCADQgDACgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAHAAARIAAABQAAAMAIAJQAIAIANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_73.setTransform(630.9,122.4);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AgfBNQgUgMgMgTQgLgUgBgZQABgZAMgTQAMgUATgNQAUgLAWgBQATABAPAHQAPAIALAOQACADAAADQgBAEgDACIgIAGQgEAFgDgCIgFgEQgGgIgKgEQgKgFgNgBQgOAAgNAIQgNAIgHAOQgHANAAAQQAAARAHANQAHAOANAJQAMAHAPABQASgBAKgHQAKgGAGgJQAEgDADAAQADAAADADIAFAEQADACABACQABAEgCADQgKAPgQALQgRAJgWABQgWgBgTgLg");
	this.shape_74.setTransform(613.4,122.4);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAADgEADQgIAHgQAGQgQAGgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPAMQgOAOgDATIBjAAIAAAAg");
	this.shape_75.setTransform(585.3,122.4);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgFCTQgEAAgCgCQgCgDAAgDIAAkVQAAgDACgCQACgDAEAAIALAAQAEAAACADQACACAAADIAAEVQAAADgCADQgCACgEAAg");
	this.shape_76.setTransform(571.2,116.1);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AgaCPQgLgFgHgGIgGgFIgDALQAAADgCACQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgIAAQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIANAAQADAAACACQACACABAEIAAB8IAFgDIAPgFQAKgCAOgBQAZABASALQASAMAJATQAKATAAAZQAAAZgKAUQgKAUgSAMQgRAMgVAAQgPAAgMgGgAgbADIgPAFIgFADIAABUIADAEIAIAKQAGAFAJAEQAIAEAMABQAOgBALgIQALgJAHgOQAGgOAAgQQAAgRgGgOQgHgNgMgIQgMgIgRAAQgMAAgJACg");
	this.shape_77.setTransform(557.2,116.3);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgFCPQgDAAgCgDQgDgCAAgDIAAiXQAAgDADgDQACgCADAAIAMAAQADAAADACQABADABADIAACXQgBADgBACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAGgGAHAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_78.setTransform(542,116.5);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AgiBSQgNgHgHgFIgCgFIAAgEIADgGIADgFQACgCADgBQADAAADABIAGAFIAOAHQAJAEAKgBQANAAAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgLALgHQAMgHATgBQAQABAMAEQAMAEAGAFQADACABADQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgCgHgBQgOABgFAFQgFAGAAAFQABAKAIAHQAJAGANAFIAbAPQAMAHAIAKQAIAKAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_79.setTransform(530.3,122.4);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AgiBSQgNgHgHgFIgCgFIAAgEIADgGIADgFQACgCADgBQADAAADABIAGAFIAOAHQAJAEAKgBQANAAAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgLALgHQAMgHATgBQAQABAMAEQAMAEAGAFQADACABADQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgCgHgBQgOABgFAFQgFAGAAAFQABAKAIAHQAJAGANAFIAbAPQAMAHAIAKQAIAKAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_80.setTransform(515.3,122.4);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_81.setTransform(497.5,122.4);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AhECVQgEAAgCgCQgCgDAAgDIAAkVQAAgDACgCQACgDAEAAIAIAAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABIACAEIADAIIAGgFQAGgEALgFQAKgEAQAAQAWAAASAMQASAMAKAUQAKAUAAAZQAAAZgLATQgKATgSAMQgSALgXABQgOgBgKgDQgKgDgFgEIgFgDIAAB/QgBADgCADQgCACgDAAgAgbh0QgKAFgFAFIgFAFIAABXIAFAEQAGADAJAEQAJADAMAAQAPAAAMgIQANgIAHgNQAGgOABgRQAAgQgGgOQgHgOgLgJQgMgIgQgBQgOABgJAFg");
	this.shape_82.setTransform(477.9,128.4);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AgfCVQgDAAgDgCQgCgCAAgEIAAiGIgaAAQgDgBgCgCQgCgCgBgCIAAgKQABgDACgCQACgDADAAIAaAAIAAg7QAAgYAJgQQAIgQAPgHQANgIASAAQASAAALAGQAMAFAFAGQADACABADIgCAFIgGALQgCADgDAAQgDAAgDgDQgFgDgIgFQgJgEgJAAQgPAAgJALQgJAKgBAYIAAA7IAwAAQADAAACADQADACAAADIAAAKQAAACgDACQgCACgDABIgwAAIAACGQAAAEgCACQgDACgDAAg");
	this.shape_83.setTransform(452.7,115.8);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_84.setTransform(434.3,122.4);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AgFCTQgEAAgCgCQgDgDABgDIAAkVQgBgDADgCQACgDAEAAIALAAQADAAADADQACACAAADIAAEVQAAADgCADQgDACgDAAg");
	this.shape_85.setTransform(410.4,116.1);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_86.setTransform(395.8,122.4);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_87.setTransform(375.5,122.4);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AhECVQgEAAgCgCQgCgDAAgDIAAkVQAAgDACgCQACgDAEAAIAIAAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABIACAEIADAIIAGgFQAGgEALgFQAKgEAQAAQAWAAASAMQASAMAKAUQAKAUAAAZQAAAZgLATQgKATgSAMQgSALgXABQgOgBgKgDQgKgDgFgEIgFgDIAAB/QgBADgCADQgCACgDAAgAgbh0QgKAFgFAFIgFAFIAABXIAFAEQAGADAJAEQAJADAMAAQAPAAAMgIQANgIAHgNQAGgOABgRQAAgQgGgOQgHgOgLgJQgMgIgQgBQgOABgJAFg");
	this.shape_88.setTransform(355.9,128.4);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAADgEADQgIAHgQAGQgQAGgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPAMQgOAOgDATIBjAAIAAAAg");
	this.shape_89.setTransform(326.3,122.4);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AA1CTQgDAAgCgCQgCgDgBgDIAAhYQAAgZgKgLQgJgMgSAAQgPAAgNAGQgLAGgIAFIgGAHIAABwQAAADgDADQgCACgDAAIgNAAQgEAAgCgCQgCgDAAgDIAAkVQAAgDACgCQACgDAEAAIANAAQADAAACADQADACAAADIAACIIAGgGQAIgFAMgFQANgGAQgBQAfABARATQARASAAAmIAABYQAAADgDADQgBACgEAAg");
	this.shape_90.setTransform(306.4,116.1);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEgBgCgBQgCgDAAgDIAAgJQAAgEACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAAEIAAAJQAAADgDADQgCABgDABIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQAAgIgGg");
	this.shape_91.setTransform(288.6,119.8);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_92.setTransform(261.9,122.1);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAADgEADQgIAHgQAGQgQAGgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPAMQgOAOgDATIBjAAIAAAAg");
	this.shape_93.setTransform(241.8,122.4);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUAAgZQAAgZAJgTQAKgTASgMQASgLAYgBQAOABALACIAPAFIAGADIAAh8QgBgEADgCQACgCAEAAIAMAAQADAAADACQACACAAAEIAAEVQAAADgCACQgDADgDAAIgJAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgHAGQgGAFgMAFQgLAGgPAAQgWAAgRgMgAgWAJQgMAIgHANQgGAOAAARQAAAQAGAOQAHAOALAJQALAIAOABQAMgBAIgEQAIgEAHgFIAIgKIADgEIAAhUIgGgDIgOgFQgJgCgMAAQgRAAgMAIg");
	this.shape_94.setTransform(221.4,116.3);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#000000").s().p("AgFCPQgEAAgCgDQgCgCAAgDIAAiXQAAgDACgDQACgCAEAAIAMAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAFgGAIAAQAIAAAGAGQAGAGAAAIQAAAJgGAFQgGAGgIAAQgIAAgFgGg");
	this.shape_95.setTransform(207.5,116.5);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#000000").s().p("ABQCYIgEgCIgDgEIhJjhIgBAAIhHDhIgDAEQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAIgGAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQgDgCAAgDIhQkZQgBgEACgDQACgDAFAAIASAAQAAAAABAAQAAAAABAAQAAABABAAQABAAAAABIADADIA6DZIACAAIBGjdQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAABAAQAAgBABAAIAGAAQABAAABABQABAAAAAAQABAAAAAAQABABAAAAIADAEIBHDdIACAAIA5jYQAAgDADgBQABgBAAAAQABAAAAgBQABAAAAAAQABAAABAAIASAAQAEAAACADQACADgBAEIhPEZIgEAFQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_96.setTransform(184.1,116.1);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#000000").s().p("AgmAnQgQgQAAgXQAAgWAQgQQAQgQAWAAQAXAAAQAQQAQAQAAAWQAAAXgQAQQgQAPgXABQgWgBgQgPg");
	this.shape_97.setTransform(1125.4,67.5);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#000000").s().p("Ag8CEQgXgHgKgJQgDgDgBgDQgCgEACgEIASgkQACgGAFgBQAEAAAFACIAJAFIAWAHQAOADAPABQAJAAAHgEQAGgEAAgJQABgIgKgIQgJgHgagLQgngOgRgVQgUgVAAgeQAAgWALgRQALgSAVgMQAWgLAiAAQAcABAWAGQAVAHALAHQAEADACAFQACAFgDAFIgQAjQgDADgEACQgFABgEgCIgJgEIgWgHQgMgDgMAAQgMAAgGAEQgFAFAAAHQAAAIAJAFQAKAFARAIQAaAJAUAMQAVAMAMARQAMARgBAaQAAAWgMATQgNASgXAMQgYALghAAQghgBgXgIg");
	this.shape_98.setTransform(1105.5,59);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#000000").s().p("ABFCKQgFgBgFgEQgDgDAAgGIAAiDQAAgbgNgPQgMgOgagBQgPAAgNAHQgOAHgHAJQgJAKgDAJIAACSQAAAHgDAEQgEADgKAAIgxAAQgFgBgEgEQgEgDgBgGIAAjwQABgGAEgEQAEgDAFgBIAZAAQAFABACACQADACACADIAIAaQAGgHAMgJQAMgJAUgIQATgHAZgBQAqABAbASQAaAUAMAeQAMAdABAkIAAB/QAAAGgFADQgDAEgFABg");
	this.shape_99.setTransform(1076.1,58.6);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#000000").s().p("AhEB5QgfgSgSghQgTgfAAgnQAAgmATggQASgfAfgTQAfgTAlgBQAnABAeATQAfATATAfQASAgAAAmQAAAngSAfQgTAhgfASQgeATgnABQglgBgfgTgAgtgwQgSAUAAAcQAAAdASAUQASATAbAAQAbAAASgTQATgUAAgdQAAgcgTgUQgSgTgbAAQgbAAgSATg");
	this.shape_100.setTransform(1042.7,59);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#000000").s().p("AgbDkQgFgBgEgDQgDgEAAgFIAAjxQAAgGADgEQAEgDAFAAIA3AAQAGAAADADQADAEABAGIAADxQgBAFgDAEQgDADgGABgAggiUQgNgNAAgUQAAgTANgNQANgNATgBQAUABANANQANANAAATQAAAUgNANQgNANgUABQgTgBgNgNg");
	this.shape_101.setTransform(1019,49.6);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#000000").s().p("AgtCeQgSgWAAgpIAAh1IgXAAQgFgBgDgDQgEgEAAgFIAAgtQAAgFAEgEQADgEAFAAIAXAAIAAhKQAAgFAEgEQAEgDAFgBIA2AAQAFAAADAEQAEADAAAFIAABLIA7AAQAFAAAEAEQAEAEAAAFIAAAtQAAAFgEAEQgEADgFABIg7AAIAABqQAAAOAGAEQAGAEAIAAQAJgBAJgCIAQgFQAFgCAEACQAEACABAGIAOAqQACAFgDAEQgCAEgFADIgPAFIgeAIQgSAEgRAAQglAAgSgXg");
	this.shape_102.setTransform(999.6,54.9);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#000000").s().p("AhYB0QgZgYAAgrQAAgkAbgYQAcgWA0gBQAUAAANADIAPAEQAAgagIgLQgJgJgSgBIgaACIgbAEQgNACgIACQgHACgEgDQgEgEgBgHIgFgjQgCgHADgEQADgDAFgCIAQgEIAhgGQAUgDAVAAQApAAAXAOQAWAOAJAaQAIAbAAAkIAACQQAAAGgEADQgDAEgGAAIgYAAQgDAAgDgCQgDgCgCgFIgIgSQgLALgUALQgUALgeABQgpAAgYgZgAgcAXQgLAJgBARQABAQAJAJQAJAJAQABQAKgBAKgEQAJgFAHgGQAHgGACgEIAAglIgLgFQgLgDgPAAQgTAAgMAKg");
	this.shape_103.setTransform(972.7,59);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#000000").s().p("AgtCeQgSgWAAgpIAAh1IgXAAQgFgBgDgDQgEgEAAgFIAAgtQAAgFAEgEQADgEAFAAIAXAAIAAhKQAAgFAEgEQAEgDAFgBIA2AAQAFAAADAEQAEADAAAFIAABLIA7AAQAFAAAEAEQAEAEAAAFIAAAtQAAAFgEAEQgEADgFABIg7AAIAABqQAAAOAGAEQAGAEAIAAQAJgBAJgCIAQgFQAFgCAEACQAEACABAGIAOAqQACAFgDAEQgCAEgFADIgPAFIgeAIQgSAEgRAAQglAAgSgXg");
	this.shape_104.setTransform(947.9,54.9);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#000000").s().p("AgaDkQgGgBgDgDQgEgEgBgFIAAjxQABgGAEgEQADgDAGAAIA2AAQAGAAADADQADAEABAGIAADxQgBAFgDAEQgDADgGABgAggiUQgNgNAAgUQAAgTANgNQAMgNAUgBQATABANANQAOANAAATQAAAUgOANQgNANgTABQgUgBgMgNg");
	this.shape_105.setTransform(928,49.6);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#000000").s().p("ACdCKQgGgBgEgEQgDgDAAgGIAAiDQAAgbgNgPQgMgOgagBQgTAAgMAHQgNAHgGAHIgGAHIABAIIAAARIAACHQAAAGgEADQgEAEgFABIgxAAQgFgBgEgEQgEgDAAgGIAAiDQAAgbgMgPQgMgOgZgBQgRAAgMAHQgLAHgHAJQgGAKgEAJIAACSQAAAGgEADQgDAEgFABIg3AAQgFgBgEgEQgDgDgBgGIAAjwQABgGADgEQAEgDAFgBIAZAAQAFABADACQADACABADIAJAaQAGgIAMgIQAMgKASgHQASgHAYgBQAcAAAVAMQAVAKAQAUQAGgHANgJQANgKATgHQATgIAYgBQArABAaASQAaAUALAeQAMAeAAAkIAAB+QAAAGgEADQgDAEgGABg");
	this.shape_106.setTransform(894.1,58.6);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#000000").s().p("AgbDkQgFgBgEgDQgDgEAAgFIAAjxQAAgGADgEQAEgDAFAAIA3AAQAFAAAEADQADAEABAGIAADxQgBAFgDAEQgEADgFABgAggiUQgNgNAAgUQAAgTANgNQANgNATgBQAUABANANQANANAAATQAAAUgNANQgNANgUABQgTgBgNgNg");
	this.shape_107.setTransform(859.7,49.6);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#000000").s().p("AgbDrQgFgBgEgEQgDgDgBgGIAAm6QABgFADgEQAEgDAFAAIA4AAQAEAAAEADQAEAEAAAFIAAG6QAAAGgEADQgEAEgEABg");
	this.shape_108.setTransform(843.5,48.9);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#000000").s().p("AgbDrQgFgBgEgEQgEgDAAgGIAAm6QAAgFAEgEQAEgDAFAAIA3AAQAGAAADADQADAEABAFIAAG6QgBAGgDADQgDAEgGABg");
	this.shape_109.setTransform(812.5,48.9);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#000000").s().p("AhYB0QgZgYAAgrQAAgkAbgYQAcgWA0gBQAUAAANADIAPAEQAAgagIgLQgJgJgSgBIgaACIgbAEQgNACgIACQgHACgEgDQgEgEgBgHIgFgjQgCgHADgEQADgDAFgCIAQgEIAhgGQAUgDAVAAQApAAAXAOQAWAOAJAaQAIAbAAAkIAACQQAAAGgEADQgDAEgGAAIgYAAQgDAAgDgCQgDgCgCgFIgIgSQgLALgUALQgUALgeABQgpAAgYgZgAgcAXQgLAJgBARQABAQAJAJQAJAJAQABQAKgBAKgEQAJgFAHgGQAHgGACgEIAAglIgLgFQgLgDgPAAQgTAAgMAKg");
	this.shape_110.setTransform(789.3,59);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#000000").s().p("Ag0B6QgggSgUgfQgUggAAgpQAAgnAUggQAUgfAggTQAhgTAlAAQAfAAAYAMQAZAMATAXQADAFgBAFQgBAGgFADIgeAeQgFADgFAAQgDgBgEgEQgJgKgLgFQgMgGgPAAQgbAAgRAUQgUATAAAcQAAAdATAUQATATAaAAQAVAAAMgIQAMgIAJgJQADgDAFgBQAEgBAFADIAcAZQAFAEACAFQABAFgDAFQgRAbgaAOQgbAPgkAAQgmAAgfgTg");
	this.shape_111.setTransform(761.7,59);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#000000").s().p("AgbDkQgFgBgEgDQgDgEAAgFIAAjxQAAgGADgEQAEgDAFAAIA3AAQAGAAADADQADAEABAGIAADxQgBAFgDAEQgDADgGABgAggiUQgNgNAAgUQAAgTANgNQANgNATgBQAUABANANQANANAAATQAAAUgNANQgNANgUABQgTgBgNgNg");
	this.shape_112.setTransform(739.2,49.6);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#000000").s().p("ABGDrQgGgBgDgEQgEgDAAgGIAAiBQAAgbgOgRQgOgPgZgBQgWABgPANQgPAMgFAWIAACNQAAAHgDADQgEADgHABIg4AAQgFgBgEgEQgDgDgBgGIAAm6QABgFADgEQAEgDAFAAIA5AAQAFAAAEADQAEAEAAAFIAADMQAKgIATgHQASgHAXgBQAqABAbAUQAaATANAdQAMAdAAAjIAACAQAAAGgEADQgEAEgFABg");
	this.shape_113.setTransform(713.9,48.9);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#000000").s().p("Ah7DuQgGgBgDgDQgEgDgBgGIAAm6QABgGAEgEQADgDAGAAIAaAAQAEAAACACQADACACAEIAJAWQAFgHAMgJQAMgIARgGQASgHAVAAQAmABAdASQAcATARAgQARAgABAnQgBAogSAgQgSAegdATQgfATglAAQgSAAgRgFQgPgGgIgEIAADEQAAAGgEADQgDAEgJAAgAgfidQgMAHgGAKQgGAJgCAHIAABRIAGAEQAGAEAMAEQALADARAAQAcAAARgTQASgUABgdQgBgdgRgTQgQgUgbAAQgRAAgMAHg");
	this.shape_114.setTransform(680.5,68.7);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#000000").s().p("AhYB0QgZgYAAgrQAAgkAbgYQAcgWA0gBQAUAAANADIAPAEQAAgagIgLQgJgJgSgBIgaACIgbAEQgNACgIACQgHACgEgDQgEgEgBgHIgFgjQgCgHADgEQADgDAFgCIAQgEIAhgGQAUgDAVAAQApAAAXAOQAWAOAJAaQAIAbAAAkIAACQQAAAGgEADQgDAEgGAAIgYAAQgDAAgDgCQgDgCgCgFIgIgSQgLALgUALQgUALgeABQgpAAgYgZgAgcAXQgLAJgBARQABAQAJAJQAJAJAQABQAKgBAKgEQAJgFAHgGQAHgGACgEIAAglIgLgFQgLgDgPAAQgTAAgMAKg");
	this.shape_115.setTransform(647.7,59);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#000000").s().p("AhQCKQgFgBgEgEQgEgDAAgGIAAjwQAAgGAEgEQAEgDAFgBIAZAAQAFABADACQADACABAEIAKAaQAEgHAKgKQAKgKAOgHQAPgHAVgBQAQAAAOAEQANADAGAGQAHAGgEAIIgZAsQgCAEgFACQgEACgEgCIgIgCIgMgCQgNABgKAEQgKAFgFAGQgGAGgCAFIAAChQAAAHgEAEQgEADgIAAg");
	this.shape_116.setTransform(624.7,58.6);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#000000").s().p("AhPDjQgegOgNgVQgOgVAAgVQABgUAIgOQAJgNAJgIQAJgHAFgCIAAgCQgHgCgMgHQgLgHgKgPQgKgPgBgYQABgTAHgOQAIgOAKgJQAJgKAIgEIAHgEIgEgIQgFgHgFgOQgFgOgBgVQABgfAPgaQAPgbAagQQAbgQAgAAIB6AAQAGAAADAEQAEADAAAGIAAAWQAAAEgCADQgCADgDABIgmAMIAHAHQAGAIAHAPQAGAPABAYQgBAagNAYQgOAYgaAPQgZAPgkABQgSAAgNgDIgVgDQgIABgIAGQgJAHAAALQAAALAIAGQAHAGAMAAIBUAAQAfAAAZALQAZALAPAVQAOAVABAeQAAAfgRAaQgQAZghAQQggAPgxAAQgwAAgfgOgAgIBkQgLAAgLACQgEABgHAEQgHAEgFAHQgFAHgBAKQABASAPALQAQAKAbAAQAcAAARgLQAQgLABgUQAAgGgEgIQgEgHgLgGQgLgFgTAAIgVAAgAgeibQgOANAAAWQAAAVAOAOQANANATAAQAVAAANgNQAMgOAAgVQAAgWgMgNQgNgNgVAAQgTAAgNANg");
	this.shape_117.setTransform(596.2,69);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#000000").s().p("AhEB5QgfgSgSghQgTgfAAgnQAAgmATggQASgfAfgTQAfgTAlgBQAnABAeATQAfATATAfQASAgAAAmQAAAngSAfQgTAhgfASQgeATgnABQglgBgfgTgAgtgwQgSAUAAAcQAAAdASAUQASATAbAAQAbAAASgTQATgUAAgdQAAgcgTgUQgSgTgbAAQgbAAgSATg");
	this.shape_118.setTransform(564.7,59);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#000000").s().p("AhAB5QgfgSgRggQgSggAAgnQAAglASggQARggAfgTQAfgTAmgBQAjAAAdARQAcAPARAdQAQAbABAlIgBAJIgBAIQAAAFgEADQgDADgFAAIirAAQABAPAIANQAIANAOAIQAOAKATAAQAPgBAOgEQAOgFAJgHQAFgDAEgBQAFAAADAEIAcAfQADAEABAFQAAAFgFAEQgQAQgaAKQgZALghAAQgngBgfgTgAA1ggQgCgUgOgNQgOgMgUgBQgTAAgPANQgOANgDAUIBlAAIAAAAg");
	this.shape_119.setTransform(534.3,59);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#000000").s().p("AhPDjQgegOgNgVQgOgVAAgVQABgUAIgOQAJgNAJgIQAJgHAFgCIAAgCQgHgCgMgHQgLgHgKgPQgKgPgBgYQABgTAHgOQAIgOAKgJQAJgKAIgEIAHgEIgEgIQgFgHgFgOQgFgOgBgVQABgfAPgaQAPgbAagQQAbgQAgAAIB6AAQAGAAADAEQAEADAAAGIAAAWQAAAEgCADQgCADgDABIgmAMIAHAHQAGAIAHAPQAGAPABAYQgBAagNAYQgOAYgaAPQgZAPgkABQgSAAgNgDIgVgDQgIABgIAGQgJAHAAALQAAALAIAGQAHAGAMAAIBUAAQAfAAAZALQAZALAPAVQAOAVABAeQAAAfgRAaQgQAZghAQQggAPgxAAQgwAAgfgOgAgIBkQgLAAgLACQgEABgHAEQgHAEgFAHQgFAHgBAKQABASAPALQAQAKAbAAQAcAAARgLQAQgLABgUQAAgGgEgIQgEgHgLgGQgLgFgTAAIgVAAgAgeibQgOANAAAWQAAAVAOAOQANANATAAQAVAAANgNQAMgOAAgVQAAgWgMgNQgNgNgVAAQgTAAgNANg");
	this.shape_120.setTransform(504.1,69);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#000000").s().p("AhEB5QgfgSgSghQgTgfAAgnQAAgmATggQASgfAfgTQAfgTAlgBQAnABAeATQAfATATAfQASAgAAAmQAAAngSAfQgTAhgfASQgeATgnABQglgBgfgTgAgtgwQgSAUAAAcQAAAdASAUQASATAbAAQAbAAASgTQATgUAAgdQAAgcgTgUQgSgTgbAAQgbAAgSATg");
	this.shape_121.setTransform(457.8,59);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#000000").s().p("ABFCKQgGgBgEgEQgDgDAAgGIAAiDQAAgbgNgPQgNgOgZgBQgPAAgOAHQgNAHgHAJQgJAKgDAJIAACSQAAAHgEAEQgDADgKAAIgyAAQgEgBgFgEQgDgDAAgGIAAjwQAAgGADgEQAFgDAEgBIAaAAQAFABACACQADACABADIAJAaQAGgHAMgJQANgJATgIQAUgHAYgBQAqABAbASQAbAUAMAeQALAdABAkIAAB/QAAAGgFADQgDAEgFABg");
	this.shape_122.setTransform(425,58.6);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#000000").s().p("AhAB5QgfgSgRggQgSggAAgnQAAglASggQARggAfgTQAfgTAmgBQAjAAAdARQAcAPARAdQAQAbABAlIgBAJIgBAIQAAAFgEADQgDADgFAAIirAAQABAPAIANQAIANAOAIQAOAKATAAQAPgBAOgEQAOgFAJgHQAFgDAEgBQAFAAADAEIAcAfQADAEABAFQAAAFgFAEQgQAQgaAKQgZALghAAQgngBgfgTgAA1ggQgCgUgOgNQgOgMgUgBQgTAAgPANQgOANgDAUIBlAAIAAAAg");
	this.shape_123.setTransform(377.9,59);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#000000").s().p("AhQCKQgFgBgEgEQgEgDAAgGIAAjwQAAgGAEgEQAEgDAFgBIAZAAQAFABADACQADACABAEIAKAaQAEgHAKgKQAKgKAOgHQAPgHAVgBQAQAAAOAEQANADAGAGQAHAGgEAIIgZAsQgCAEgFACQgEACgEgCIgIgCIgMgCQgNABgKAEQgKAFgFAGQgGAGgCAFIAAChQAAAHgEAEQgEADgIAAg");
	this.shape_124.setTransform(353.3,58.6);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#000000").s().p("AhYB0QgZgYAAgrQAAgkAbgYQAcgWA0gBQAUAAANADIAPAEQAAgagIgLQgJgJgSgBIgaACIgbAEQgNACgIACQgHACgEgDQgEgEgBgHIgFgjQgCgHADgEQADgDAFgCIAQgEIAhgGQAUgDAVAAQApAAAXAOQAWAOAJAaQAIAbAAAkIAACQQAAAGgEADQgDAEgGAAIgYAAQgDAAgDgCQgDgCgCgFIgIgSQgLALgUALQgUALgeABQgpAAgYgZgAgcAXQgLAJgBARQABAQAJAJQAJAJAQABQAKgBAKgEQAJgFAHgGQAHgGACgEIAAglIgLgFQgLgDgPAAQgTAAgMAKg");
	this.shape_125.setTransform(324.8,59);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#000000").s().p("AhAB5QgfgSgRggQgSggAAgnQAAglASggQARggAfgTQAfgTAmgBQAjAAAdARQAcAPARAdQAQAbABAlIgBAJIgBAIQAAAFgEADQgDADgFAAIirAAQABAPAIANQAIANAOAIQAOAKATAAQAPgBAOgEQAOgFAJgHQAFgDAEgBQAFAAADAEIAcAfQADAEABAFQAAAFgFAEQgQAQgaAKQgZALghAAQgngBgfgTgAA1ggQgCgUgOgNQgOgMgUgBQgTAAgPANQgOANgDAUIBlAAIAAAAg");
	this.shape_126.setTransform(281.8,59);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#000000").s().p("AhQCKQgFgBgEgEQgEgDAAgGIAAjwQAAgGAEgEQAEgDAFgBIAZAAQAFABADACQADACABAEIAKAaQAEgHAKgKQAKgKAOgHQAPgHAVgBQAQAAAOAEQANADAGAGQAHAGgEAIIgZAsQgCAEgFACQgEACgEgCIgIgCIgMgCQgNABgKAEQgKAFgFAGQgGAGgCAFIAAChQAAAHgEAEQgEADgIAAg");
	this.shape_127.setTransform(257.3,58.6);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#000000").s().p("AhAB5QgfgSgRggQgSggAAgnQAAglASggQARggAfgTQAfgTAmgBQAjAAAdARQAcAPARAdQAQAbABAlIgBAJIgBAIQAAAFgEADQgDADgFAAIirAAQABAPAIANQAIANAOAIQAOAKATAAQAPgBAOgEQAOgFAJgHQAFgDAEgBQAFAAADAEIAcAfQADAEABAFQAAAFgFAEQgQAQgaAKQgZALghAAQgngBgfgTgAA1ggQgCgUgOgNQgOgMgUgBQgTAAgPANQgOANgDAUIBlAAIAAAAg");
	this.shape_128.setTransform(229.2,59);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#000000").s().p("ABGDrQgGgBgDgEQgEgDAAgGIAAiBQAAgbgOgRQgOgPgZgBQgWABgPANQgPAMgFAWIAACNQAAAHgDADQgEADgHABIg4AAQgFgBgEgEQgDgDgBgGIAAm6QABgFADgEQAEgDAFAAIA5AAQAFAAAEADQAEAEAAAFIAADMQAKgIATgHQASgHAXgBQAqABAbAUQAaATANAdQAMAdAAAjIAACAQAAAGgEADQgEAEgFABg");
	this.shape_129.setTransform(196.9,48.9);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#000000").s().p("AgeDrQgFgBgEgEQgEgDAAgGIAAl2IhnAAQgFgBgEgDQgDgDAAgGIAAg3QAAgFADgEQAEgDAFAAIEkAAQAGAAADADQAEAEAAAFIAAA3QAAAGgEADQgDADgGABIhnAAIAAF2QAAAGgDADQgEAEgFABg");
	this.shape_130.setTransform(162.5,48.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.TextBoi, new cjs.Rectangle(0,0,1281.4,186.8), null);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.GlobeEarth();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(0,0,441,219), null);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//this.stop();
		
		iWell = localStorage.getItem("15018394-checkThree")
		console.log(iWell);
		
		if (iWell == 0) {
			//this.gotoAndStop(1);
			console.log("On");
			this.play();
		} else {
			//this.gotoAndStop(2);
			console.log("off");
			this.stop();
		}
		
		//console.log(this);
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Layer 1
	this.instance = new lib.unCheckbox();
	this.instance.parent = this;

	this.instance_1 = new lib.Checkbox();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,58,58);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//this.stop();
		
		iWell = localStorage.getItem("15018394-checkTwo")
		console.log(iWell);
		
		if (iWell == 0) {
			//this.gotoAndStop(1);
			console.log("On");
			this.play();
		} else {
			//this.gotoAndStop(2);
			console.log("off");
			this.stop();
		}
		
		//console.log(this);
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Layer 1
	this.instance = new lib.unCheckbox();
	this.instance.parent = this;

	this.instance_1 = new lib.Checkbox();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,58,58);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//this.stop();
		
		iWell = localStorage.getItem("15018394-checkOne")
		console.log(iWell);
		
		if (iWell == 0) {
			//this.gotoAndStop(1);
			console.log("On");
			this.play();
		} else {
			//this.gotoAndStop(2);
			console.log("off");
			this.stop();
		}
		
		//console.log(this);
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Layer 1
	this.instance = new lib.unCheckbox();
	this.instance.parent = this;

	this.instance_1 = new lib.Checkbox();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,58,58);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ManUS();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,1280,1024), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.GirlEur();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,1280,1024), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ManAus();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,1280,1024), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EBE8BakMAAAitdMAolAAAMAAACtdgEgc6BZ7MAAAgjGIGnAAMAAAgjPMAykAAAMAAAAjPIIZAAMAAAAjGgEhtgBYeMAAAizBMAoBAAAMAAACzBg");
	this.shape.setTransform(120.1,-413);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-580.8,-992.6,1401.9,1159.3), null);


(lib.btnRight = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.rightNav();
	this.instance.parent = this;
	this.instance.setTransform(30,0);

	this.instance_1 = new lib.rightbtn();
	this.instance_1.parent = this;
	this.instance_1.setTransform(4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(30,0,97,1024);


(lib.backtomain = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.returnbutton();
	this.instance.parent = this;

	this.instance_1 = new lib.returnbuttonhover();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,230,95);


// stage content:
(lib.Untitled5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var aOfficeNoise = new Audio('sounds/roomNoise.mp3');
		var aClick = new Audio('sounds/click.mp3');
		aOfficeNoise.play();
		
		var iCurrentFrame = 0;
		
		//var checkBox = [0,0,0];
		
		if (localStorage.getItem("15018394-checkOne") == null) {
			localStorage.setItem("15018394-checkOne",0);
			localStorage.setItem("15018394-checkTwo",0);
			localStorage.setItem("15018394-checkThree",0);
		}
		
		exportRoot.backToMain.addEventListener("click", buttonClicked.bind(this));
		exportRoot.btnRight.addEventListener("click", buttonRightClick.bind(this));
		
		function buttonClicked()
		{
			this.gotoAndPlay(75);
			aClick.play();
		}
		
		function buttonRightClick()
		{
			this.play();
			aClick.play();
		}
		
		//Checkbox control
		exportRoot.checkOne.cursor = "pointer";
		exportRoot.checkTwo.cursor = "pointer";
		exportRoot.checkThree.cursor = "pointer";
		
		exportRoot.checkOne.addEventListener("click", checkOneClick.bind(this));
		exportRoot.checkTwo.addEventListener("click", checkTwoClick.bind(this));
		exportRoot.checkThree.addEventListener("click", checkThreeClick.bind(this));
		
		function checkOneClick() {	
			aClick.play();
			checkBox = localStorage.getItem("15018394-checkOne");
		
			if (checkBox == 0) {
				checkBox = 1;
			} else {
				checkBox = 0;
			}
			
			localStorage.setItem("15018394-checkOne",checkBox);
			exportRoot.checkOne.play();
		}
		
		function checkTwoClick() {
			aClick.play();
			checkBox = localStorage.getItem("15018394-checkTwo");
		
			if (checkBox == 0) {
				checkBox = 1;
			} else {
				checkBox = 0;
			}
			
			localStorage.setItem("15018394-checkTwo",checkBox);
			exportRoot.checkTwo.play();
		}
		
		function checkThreeClick() {
			aClick.play();
			checkBox = localStorage.getItem("15018394-checkThree");
		
			if (checkBox == 0) {
				checkBox = 1;
			} else {
				checkBox = 0;
			}
			
			localStorage.setItem("15018394-checkThree",checkBox);
			exportRoot.checkThree.play();
		}
	}
	this.frame_24 = function() {
		this.stop();
		
		iCurrentFrame = 1;
	}
	this.frame_44 = function() {
		this.stop();
	}
	this.frame_64 = function() {
		this.stop();
	}
	this.frame_74 = function() {
		//console.log(exportRoot.checkOne);
		//this.gotoAndPlay(14);
	}
	this.frame_87 = function() {
		this.stop();
		window.open("index.html","_self");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(24).call(this.frame_24).wait(20).call(this.frame_44).wait(20).call(this.frame_64).wait(10).call(this.frame_74).wait(13).call(this.frame_87).wait(1));

	// Layer 11
	this.instance = new lib.TextBoi();
	this.instance.parent = this;
	this.instance.setTransform(1830.2,185.7,1,1,0,0,0,640.7,161.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(8).to({_off:false},0).wait(1).to({regX:638.8,regY:103.4,x:1729.2,y:127.3},0).wait(1).to({x:1630.1},0).wait(1).to({x:1530.9},0).wait(1).to({x:1431.8},0).wait(1).to({x:1332.7},0).wait(1).to({x:1233.6},0).wait(1).to({x:1134.4},0).wait(1).to({x:1035.3},0).wait(1).to({x:936.2},0).wait(1).to({x:837.1},0).wait(1).to({x:737.9},0).wait(1).to({x:638.8},0).wait(55).to({x:547.3},0).wait(1).to({x:455.8},0).wait(1).to({x:364.3},0).wait(1).to({x:272.8},0).wait(1).to({x:181.3},0).wait(1).to({x:89.8},0).wait(1).to({x:-1.6},0).wait(1).to({x:-93.2},0).wait(1).to({x:-184.6},0).wait(1).to({x:-276.2},0).wait(1).to({x:-367.7},0).wait(1).to({x:-459.2},0).wait(1).to({x:-550.7},0).wait(1));

	// Layer 2
	this.instance_1 = new lib.Symbol1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(631.3,954.3,1,1,0,0,0,128.8,54.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regX:120.1,regY:-413,x:622.6,y:486.5,alpha:0.941},0).wait(1).to({alpha:0.882},0).wait(1).to({alpha:0.824},0).wait(1).to({alpha:0.765},0).wait(1).to({alpha:0.706},0).wait(1).to({alpha:0.647},0).wait(1).to({alpha:0.588},0).wait(1).to({alpha:0.529},0).wait(1).to({alpha:0.471},0).wait(1).to({alpha:0.412},0).wait(1).to({alpha:0.353},0).wait(1).to({alpha:0.294},0).wait(1).to({alpha:0.235},0).wait(1).to({alpha:0.176},0).wait(1).to({alpha:0.118},0).wait(1).to({alpha:0.059},0).wait(1).to({alpha:0},0).wait(58).to({alpha:0.077},0).wait(1).to({alpha:0.154},0).wait(1).to({alpha:0.231},0).wait(1).to({alpha:0.308},0).wait(1).to({alpha:0.385},0).wait(1).to({alpha:0.462},0).wait(1).to({alpha:0.538},0).wait(1).to({alpha:0.615},0).wait(1).to({alpha:0.692},0).wait(1).to({alpha:0.769},0).wait(1).to({alpha:0.846},0).wait(1).to({alpha:0.923},0).wait(1).to({alpha:1},0).wait(1));

	// Layer 13
	this.instance_2 = new lib.Globeshadow();
	this.instance_2.parent = this;
	this.instance_2.setTransform(580,24);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(88));

	// Layer 16 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AtmN0QloluAAoGQAAoFFoluQFpluH9AAQH+AAFpFuQFoFuAAIFQAAIGloFuQlpFun+AAQn9AAlplug");
	mask.setTransform(655.1,761.1);

	// Layer 15
	this.instance_3 = new lib.Symbol8();
	this.instance_3.parent = this;
	this.instance_3.setTransform(403.5,758.5,1,1,0,0,0,220.5,109.5);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(12).to({_off:false},0).wait(1).to({x:413.3},0).wait(1).to({x:423},0).wait(1).to({x:432.8},0).wait(1).to({x:442.5},0).wait(1).to({x:452.3},0).wait(1).to({x:462},0).wait(1).to({x:471.8},0).wait(1).to({x:481.5},0).wait(1).to({x:491.3},0).wait(1).to({x:501},0).wait(1).to({x:510.8},0).wait(1).to({x:520.5},0).wait(1).to({x:525.4},0).wait(1).to({x:530.3},0).wait(1).to({x:535.1},0).wait(1).to({x:540},0).wait(1).to({x:544.9},0).wait(1).to({x:549.8},0).wait(1).to({x:554.6},0).wait(1).to({x:559.5},0).wait(1).to({x:564.4},0).wait(1).to({x:569.3},0).wait(1).to({x:574.1},0).wait(1).to({x:579},0).wait(1).to({x:583.9},0).wait(1).to({x:588.8},0).wait(1).to({x:593.6},0).wait(1).to({x:598.5},0).wait(1).to({x:603.4},0).wait(1).to({x:608.3},0).wait(1).to({x:613.1},0).wait(1).to({x:618},0).wait(1).to({x:626.8},0).wait(1).to({x:635.6},0).wait(1).to({x:644.3},0).wait(1).to({x:653.1},0).wait(1).to({x:661.9},0).wait(1).to({x:670.7},0).wait(1).to({x:679.4},0).wait(1).to({x:688.2},0).wait(1).to({x:697},0).wait(1).to({x:705.8},0).wait(1).to({x:714.5},0).wait(1).to({x:723.3},0).wait(1).to({x:732.1},0).wait(1).to({x:740.9},0).wait(1).to({x:749.6},0).wait(1).to({x:758.4},0).wait(1).to({x:767.2},0).wait(1).to({x:776},0).wait(1).to({x:784.7},0).wait(1).to({x:793.5},0).wait(1).to({x:800.8},0).wait(1).to({x:808.1},0).wait(1).to({x:815.4},0).wait(1).to({x:822.7},0).wait(1).to({x:830},0).wait(1).to({x:837.3},0).wait(1).to({x:844.6},0).wait(1).to({x:851.9},0).wait(1).to({x:859.2},0).wait(1).to({x:866.5},0).wait(1).to({x:873.8},0).wait(1).to({x:881.2},0).wait(1).to({x:888.5},0).wait(1).to({x:895.8},0).wait(1).to({x:903.1},0).wait(1).to({x:910.4},0).wait(1).to({x:917.7},0).wait(1).to({x:925},0).wait(1).to({x:932.3},0).wait(1).to({x:939.6},0).wait(1).to({x:946.9},0).wait(1).to({x:954.2},0).wait(1).to({x:961.5},0).wait(1));

	// Globe
	this.instance_4 = new lib.Globe();
	this.instance_4.parent = this;
	this.instance_4.setTransform(529,638);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(88));

	// Layer 5
	this.btnRight = new lib.btnRight();
	this.btnRight.parent = this;
	this.btnRight.setTransform(1216.5,512,1,1,0,0,0,63.5,512);
	new cjs.ButtonHelper(this.btnRight, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.btnRight).wait(88));

	// Layer 10
	this.checkThree = new lib.Symbol7();
	this.checkThree.parent = this;
	this.checkThree.setTransform(2128.1,896.9,1,1,0,0,0,29,29);
	this.checkThree._off = true;

	this.timeline.addTween(cjs.Tween.get(this.checkThree).wait(54).to({_off:false},0).wait(1).to({x:2013},0).wait(1).to({x:1898},0).wait(1).to({x:1782.9},0).wait(1).to({x:1667.9},0).wait(1).to({x:1552.8},0).wait(1).to({x:1437.8},0).wait(1).to({x:1322.7},0).wait(1).to({x:1207.7},0).wait(1).to({x:1092.6},0).wait(1).to({x:977.6},0).wait(1).to({x:872.3},0).wait(1).to({x:767},0).wait(1).to({x:661.7},0).wait(1).to({x:556.4},0).wait(1).to({x:451.1},0).wait(1).to({x:345.8},0).wait(1).to({x:240.5},0).wait(1).to({x:135.2},0).wait(1).to({x:29.9},0).wait(1).to({x:-75.4},0).to({_off:true},1).wait(13));

	// man3
	this.instance_5 = new lib.Symbol4();
	this.instance_5.parent = this;
	this.instance_5.setTransform(1793,512,1,1,0,0,0,640,512);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(54).to({_off:false},0).wait(1).to({x:1677.9},0).wait(1).to({x:1562.7},0).wait(1).to({x:1447.6},0).wait(1).to({x:1332.4},0).wait(1).to({x:1217.3},0).wait(1).to({x:1102.1},0).wait(1).to({x:987},0).wait(1).to({x:871.8},0).wait(1).to({x:756.7},0).wait(1).to({x:641.5},0).wait(1).to({x:536.2},0).wait(1).to({x:430.8},0).wait(1).to({x:325.5},0).wait(1).to({x:220.1},0).wait(1).to({x:114.8},0).wait(1).to({x:9.4},0).wait(1).to({x:-95.9},0).wait(1).to({x:-201.3},0).wait(1).to({x:-306.6},0).wait(1).to({x:-412},0).to({_off:true},1).wait(13));

	// man2Box
	this.checkTwo = new lib.Symbol6();
	this.checkTwo.parent = this;
	this.checkTwo.setTransform(2053.6,896.9,1,1,0,0,0,29,29);
	this.checkTwo._off = true;

	this.timeline.addTween(cjs.Tween.get(this.checkTwo).wait(34).to({_off:false},0).wait(1).to({x:1946.4},0).wait(1).to({x:1839.1},0).wait(1).to({x:1731.9},0).wait(1).to({x:1624.6},0).wait(1).to({x:1517.4},0).wait(1).to({x:1410.1},0).wait(1).to({x:1302.9},0).wait(1).to({x:1195.6},0).wait(1).to({x:1088.4},0).wait(1).to({x:981.1},0).wait(1).to({x:877.8},0).wait(1).to({x:774.4},0).wait(1).to({x:671.1},0).wait(1).to({x:567.7},0).wait(1).to({x:464.4},0).wait(1).to({x:361},0).wait(1).to({x:257.7},0).wait(1).to({x:154.3},0).wait(1).to({x:51},0).wait(1).to({x:-52.4},0).to({_off:true},1).wait(33));

	// man2
	this.instance_6 = new lib.Symbol3();
	this.instance_6.parent = this;
	this.instance_6.setTransform(1708,512,1,1,0,0,0,640,512);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(34).to({_off:false},0).wait(1).to({x:1601.4},0).wait(1).to({x:1494.9},0).wait(1).to({x:1388.3},0).wait(1).to({x:1281.7},0).wait(1).to({x:1175.1},0).wait(1).to({x:1068.6},0).wait(1).to({x:962},0).wait(1).to({x:855.4},0).wait(1).to({x:748.8},0).wait(1).to({x:642.3},0).wait(1).to({x:539.4},0).wait(1).to({x:436.5},0).wait(1).to({x:333.6},0).wait(1).to({x:230.7},0).wait(1).to({x:127.8},0).wait(1).to({x:24.9},0).wait(1).to({x:-78},0).wait(1).to({x:-180.9},0).wait(1).to({x:-283.8},0).wait(1).to({x:-386.7},0).to({_off:true},1).wait(33));

	// manAusBox
	this.checkOne = new lib.Symbol5();
	this.checkOne.parent = this;
	this.checkOne.setTransform(2053.6,896.9,1,1,0,0,0,29,29);
	this.checkOne._off = true;

	this.timeline.addTween(cjs.Tween.get(this.checkOne).wait(13).to({_off:false},0).wait(1).to({x:1955.9},0).wait(1).to({x:1858.1},0).wait(1).to({x:1760.5},0).wait(1).to({x:1662.7},0).wait(1).to({x:1565},0).wait(1).to({x:1467.3},0).wait(1).to({x:1369.6},0).wait(1).to({x:1271.8},0).wait(1).to({x:1174.1},0).wait(1).to({x:1076.3},0).wait(1).to({x:978.6},0).wait(1).to({x:876.1},0).wait(1).to({x:773.6},0).wait(1).to({x:671.1},0).wait(1).to({x:568.6},0).wait(1).to({x:466.1},0).wait(1).to({x:363.6},0).wait(1).to({x:261.1},0).wait(1).to({x:158.6},0).wait(1).to({x:56.1},0).wait(1).to({x:-46.4},0).to({_off:true},1).wait(53));

	// manAus
	this.instance_7 = new lib.Symbol2();
	this.instance_7.parent = this;
	this.instance_7.setTransform(1711,512,1,1,0,0,0,640,512);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(13).to({_off:false},0).wait(1).to({x:1613.6},0).wait(1).to({x:1516.3},0).wait(1).to({x:1419},0).wait(1).to({x:1321.5},0).wait(1).to({x:1224.2},0).wait(1).to({x:1126.9},0).wait(1).to({x:1029.6},0).wait(1).to({x:932.1},0).wait(1).to({x:834.7},0).wait(1).to({x:737.4},0).wait(1).to({x:640},0).wait(1).to({x:537.1},0).wait(1).to({x:434.2},0).wait(1).to({x:331.3},0).wait(1).to({x:228.4},0).wait(1).to({x:125.5},0).wait(1).to({x:22.6},0).wait(1).to({x:-80.3},0).wait(1).to({x:-183.2},0).wait(1).to({x:-286.1},0).wait(1).to({x:-389},0).to({_off:true},1).wait(53));

	// backButton
	this.backToMain = new lib.backtomain();
	this.backToMain.parent = this;
	this.backToMain.setTransform(645,961.5,1,1,0,0,0,115,47.5);
	new cjs.ButtonHelper(this.backToMain, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.backToMain).wait(88));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(561.6,418.9,1401.9,1159.3);
// library properties:
lib.properties = {
	width: 1280,
	height: 1024,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/Scene4_atlas_.png", id:"Scene4_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;