(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.fern = function() {
	this.initialize(img.fern);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,185,402);


(lib.Groundsand = function() {
	this.initialize(img.Groundsand);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1280,1024);


(lib.Groundwork = function() {
	this.initialize(img.Groundwork);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1280,1024);


(lib.laptop = function() {
	this.initialize(img.laptop);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,459,227);


(lib.returnbuttonhover = function() {
	this.initialize(img.returnbuttonhover);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,230,95);


(lib.returnbutton = function() {
	this.initialize(img.returnbutton);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,230,95);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.TextBoi = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgPAQQgIgGAAgKQAAgJAIgHQAGgHAJAAQAKAAAHAHQAHAHAAAJQAAAKgHAGQgHAIgKAAQgJAAgGgIg");
	this.shape.setTransform(769.9,303.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Ag7CTQgFgBgCgCQgCgDACgFIA2h0IhOicQgCgFABgCQACgDAFAAIATAAIAEACQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAABIA+CAIAAAAIA7iAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAQAAQAFAAACADQABADgCAEIiAEWIgDADQAAABgBAAQAAAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(755.3,303.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgiBSQgNgHgHgFIgCgFIAAgEIADgGIADgFQACgCADgBQADAAADABIAGAFIAOAGQAJAFAKAAQANgBAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgKALgIQAMgHATgBQAQABAMAEQAMAEAGAEQADADABADQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgCgHgBQgOABgFAFQgFAGAAAFQABAKAIAHQAJAGANAFIAbAPQAMAHAIAKQAIAKAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_2.setTransform(738.3,297.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfgBQAJAAAIACIAOADIAFABQABgXgGgMQgFgLgRABQgRgBgOAEIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgDgKQgBgEABgCQABgCADgCIAKgCQAIgDAMgDQANgCAPgBQAVAAAMAJQALAGAFAQQAEARAAAYIAABcQAAAEgCACQgDACgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAHAAARIAAABQAAAMAIAJQAIAIANAAQAPAAANgHQAMgIAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_3.setTransform(721.2,297.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgoBMQgSgMgKgTQgKgVAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIANANAHQAMAIAOAAQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAGQAAACgEADQgIAGgQAHQgQAGgWABQgYgBgTgMgAAygQQgBgMgGgLQgGgJgKgHQgLgGgNAAQgUAAgPAMQgOANgDAUIBjAAIAAAAg");
	this.shape_4.setTransform(703.4,297.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgiBSQgNgHgHgFIgCgFIAAgEIADgGIADgFQACgCADgBQADAAADABIAGAFIAOAGQAJAFAKAAQANgBAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgKALgIQAMgHATgBQAQABAMAEQAMAEAGAEQADADABADQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgCgHgBQgOABgFAFQgFAGAAAFQABAKAIAHQAJAGANAFIAbAPQAMAHAIAKQAIAKAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_5.setTransform(677.2,297.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgFCPQgDAAgCgDQgDgCAAgDIAAiXQAAgDADgDQACgCADAAIAMAAQADAAACACQACADABADIAACXQgBADgCACQgCADgDAAgAgOhsQgFgFAAgJQAAgIAFgGQAGgGAIAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgIAAgGgGg");
	this.shape_6.setTransform(665.1,291.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgiBSQgNgHgHgFIgCgFIAAgEIADgGIADgFQACgCADgBQADAAADABIAGAFIAOAGQAJAFAKAAQANgBAHgFQAHgGAAgIQAAgMgJgGQgKgIgRgIIgWgMQgLgHgHgKQgIgLAAgNQAAgKAFgJQAGgKALgIQAMgHATgBQAQABAMAEQAMAEAGAEQADADABADQABAEgCAEIgEAHQgCADgDABQgEABgDgCIgFgCIgNgFQgIgCgHgBQgOABgFAFQgFAGAAAFQABAKAIAHQAJAGANAFIAbAPQAMAHAIAKQAIAKAAAOQAAANgIALQgHALgNAHQgNAGgRABQgUgCgOgFg");
	this.shape_7.setTransform(644.1,297.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_8.setTransform(626.1,297.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgIgPAAQgPAAgMAIg");
	this.shape_9.setTransform(605.5,297.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgFCPQgDAAgCgDQgDgCAAgDIAAiXQAAgDADgDQACgCADAAIAMAAQADAAACACQADADAAADIAACXQAAADgDACQgCADgDAAgAgOhsQgFgFAAgJQAAgIAFgGQAGgGAIAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgIAAgGgGg");
	this.shape_10.setTransform(590.9,291.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgQBrQgJgFgCgLQgDgKAAgNIAAhkIgVAAQgEgBgCgBQgCgDAAgDIAAgJQAAgEACgCQACgCAEgBIAVAAIAAguQAAgDADgDQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAAEIAAAJQAAADgDADQgCABgDABIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAACgEADIgLAFQgHADgKADQgKADgKAAQgQAAgIgHg");
	this.shape_11.setTransform(579.3,294.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfgBQAJAAAIACIAOADIAFABQABgXgGgMQgFgLgRABQgRgBgOAEIgTAGQgDABgCgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgDgKQgBgEABgCQABgCADgCIAKgCQAIgDAMgDQANgCAPgBQAVAAAMAJQALAGAFAQQAEARAAAYIAABcQAAAEgCACQgDACgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAHAAARIAAABQAAAMAIAJQAIAIANAAQAPAAANgHQAMgIAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_12.setTransform(562.8,297.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgfBNQgUgMgMgTQgLgUgBgZQABgZAMgTQAMgVATgMQAUgLAWgBQATABAPAHQAPAIALAOQACADAAADQgBAEgDACIgIAGQgEAFgDgCIgFgEQgGgIgKgEQgKgGgNAAQgOABgNAHQgNAIgHANQgHAOAAAQQAAARAHANQAHAOANAJQAMAHAPABQASgBAKgHQAKgGAGgJQAEgDADAAQADAAADADIAFADQADADABACQABAEgCADQgKAPgQALQgRAJgWABQgWgBgTgLg");
	this.shape_13.setTransform(545.3,297.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgTQALgUATgMQASgMAXgBQAYABASAMQATAMALAUQALATABAYQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgIgPAAQgPAAgMAIg");
	this.shape_14.setTransform(525.9,297.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgFCTQgEAAgCgCQgCgCAAgEIAAkVQAAgDACgCQACgDAEAAIALAAQAEAAACADQACACAAADIAAEVQAAAEgCACQgCACgEAAg");
	this.shape_15.setTransform(511.3,291);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgFCTQgEAAgCgDQgDgCABgDIAAkVQgBgDADgCQACgDAEAAIALAAQADAAADADQACACAAADIAAEVQAAADgCACQgDADgDAAg");
	this.shape_16.setTransform(1005.3,253);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AguBMQgOgJgGgRQgGgRAAgXIAAhXQAAgDACgDQADgCADAAIANAAQAEAAACACQACADAAADIAABXQAAAYAKAMQAKAMASAAQAPAAALgGQAMgGAFgGIAGgGIAAgIIAAgRIAAgfIAAg3QAAgDADgDQACgCADAAIANAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgFIgDgLIgHAGQgGAFgMAFQgMAGgRAAQgYAAgPgKg");
	this.shape_17.setTransform(990.5,259.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgeCVQgEAAgDgCQgBgCAAgEIAAiGIgaAAQgEgBgCgCQgCgCAAgCIAAgKQAAgDACgCQACgDAEAAIAaAAIAAg7QAAgYAIgQQAJgQAOgHQANgIATAAQARAAALAGQAMAFAFAGQADACAAADIgBAFIgHALQgBADgDAAQgDAAgEgDQgDgDgJgFQgIgEgKAAQgPAAgJALQgKAKAAAYIAAA7IAwAAQADAAACADQADACAAADIAAAKQAAACgDACQgCACgDABIgwAAIAACGQAAAEgCACQgDACgDAAg");
	this.shape_18.setTransform(975.3,252.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgFCPQgEAAgCgDQgCgCAAgDIAAiXQAAgDACgDQACgCAEAAIAMAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAFgGAIAAQAIAAAGAGQAGAGAAAIQAAAJgGAFQgGAGgIAAQgIAAgFgGg");
	this.shape_19.setTransform(962.6,253.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgCQgCgDAAgDIAAgKQAAgDACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAADIAAAKQAAADgDADQgCACgDAAIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQgBgIgFg");
	this.shape_20.setTransform(951,256.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AguBMQgOgJgGgRQgGgRAAgXIAAhXQAAgDACgDQADgCADAAIANAAQAEAAACACQACADAAADIAABXQAAAYAKAMQAKAMASAAQAPAAALgGQAMgGAFgGIAGgGIAAgIIAAgRIAAgfIAAg3QAAgDADgDQACgCADAAIANAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgFIgDgLIgHAGQgGAFgMAFQgMAGgRAAQgYAAgPgKg");
	this.shape_21.setTransform(933.5,259.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfAAQAJAAAIABIAOACIAFACQABgYgGgLQgFgKgRgBQgRABgOADIgTAFQgDACgCgCQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgDAMgCQANgCAPgBQAVABAMAHQALAHAFARQAEAQAAAYIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAIAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_22.setTransform(914.1,259.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgoBMQgSgMgKgUQgKgUAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIAMANAIQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAACgEAEQgIAHgQAFQgQAHgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPANQgOANgDATIBjAAIAAAAg");
	this.shape_23.setTransform(896.3,259.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgaCPQgLgFgHgGIgGgFIgDALQAAADgCACQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgIAAQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIANAAQADAAACACQACACABAEIAAB8IAFgDIAPgFQAKgCAOgBQAZABASALQASAMAJATQAKATAAAZQAAAZgKAUQgKAUgSAMQgRAMgVAAQgPAAgMgGgAgbADIgPAFIgFADIAABUIADAEIAIAKQAGAFAJAEQAIAEAMABQAOgBALgIQALgJAHgOQAGgOAAgQQAAgRgGgOQgHgNgMgIQgMgIgRAAQgMAAgJACg");
	this.shape_24.setTransform(877.1,253.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgXALgVQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAVABAXQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_25.setTransform(846.9,259.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgCQgCgDAAgDIAAgKQAAgDACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAADIAAAKQAAADgDADQgCACgDAAIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQgBgIgFg");
	this.shape_26.setTransform(829.6,256.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgtCPQgSgJgJgNQgIgNAAgPQAAgMAGgIQAFgIAFgFIAJgGIAAgBQgGgBgHgFQgHgEgGgIQgEgJgBgNQABgMADgIQAEgJAGgGIAJgJIAFgDIgEgFIgGgPQgDgJgBgNQABgUAIgRQAJgQAQgLQAPgKAXAAIBGAAQADAAADACQACACAAAEIAAAHIgBAFQgBAAAAABQgBAAAAAAQgBABAAAAQAAAAgBAAIgWAFIAEAFQAFAEAEALQAFAKAAARQAAATgIAQQgJAQgQAKQgPAKgVAAQgOAAgIgCQgKgDgEgCIgEgDIgFADQgFACgEAGQgFAFAAAIQAAAIAGAGQAFAGAMABIA8AAQASAAAOAFQAOAGAJAMQAIAMAAASQAAASgLAQQgMAPgTAKQgTAJgaAAQgbAAgSgIgAgaA7IgKAFQgGAEgDAGQgFAGAAAJQAAAQAOAJQAOAKAWAAQANAAANgFQANgFAIgIQAJgJAAgNIgCgJQgCgHgHgFQgHgGgOAAIguAAgAgfhvQgMANgBAVQABAVAMANQALANAUAAQATAAAKgNQAMgNAAgVQAAgVgMgNQgKgNgTAAQgUAAgLANg");
	this.shape_27.setTransform(803.9,265.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_28.setTransform(783.6,259);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgFCPQgEAAgCgDQgCgCAAgDIAAiXQAAgDACgDQACgCAEAAIAMAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAFgGAIAAQAIAAAGAGQAGAGAAAIQAAAJgGAFQgGAGgIAAQgIAAgFgGg");
	this.shape_29.setTransform(768.6,253.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgCQgCgDAAgDIAAgKQAAgDACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAADIAAAKQAAADgDADQgCACgDAAIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQgBgIgFg");
	this.shape_30.setTransform(757,256.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfAAQAJAAAIABIAOACIAFACQABgYgGgLQgFgKgRgBQgRABgOADIgTAFQgDACgCgCQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgDAMgCQANgCAPgBQAVABAMAHQALAHAFARQAEAQAAAYIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAIAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_31.setTransform(740.5,259.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgfBNQgUgLgMgVQgLgTgBgaQABgXAMgVQAMgUATgLQAUgMAWgBQATAAAPAIQAPAHALAPQACADAAADQgBADgDADIgIAHQgEADgDgBIgFgEQgGgIgKgEQgKgFgNgBQgOAAgNAIQgNAIgHAOQgHANAAAQQAAARAHANQAHAOANAJQAMAHAPABQASgBAKgHQAKgGAGgJQAEgDADAAQADAAADADIAFAEQADACABACQABAEgCADQgKAQgQAKQgRAJgWABQgWgBgTgLg");
	this.shape_32.setTransform(723,259.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgXALgVQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAVABAXQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_33.setTransform(703.6,259.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgGCTQgDAAgCgDQgDgCAAgDIAAkVQAAgDADgCQACgDADAAIANAAQADAAACADQACACABADIAAEVQgBADgCACQgCADgDAAg");
	this.shape_34.setTransform(689,253);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgoBMQgSgMgKgUQgKgUAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIAMANAIQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAACgEAEQgIAHgQAFQgQAHgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPANQgOANgDATIBjAAIAAAAg");
	this.shape_35.setTransform(675,259.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_36.setTransform(659.6,259);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUgBgZQABgZAJgTQAKgTASgMQASgLAYgBQAOABALACIAPAFIAFADIAAh8QABgEACgCQACgCADAAIAOAAQACAAADACQACACAAAEIAAEVQAAADgCACQgDADgCAAIgJAAQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCAAgDIgDgLIgGAGQgHAFgLAFQgMAGgPAAQgVAAgSgMgAgXAJQgMAIgGANQgGAOAAARQAAAQAGAOQAGAOALAJQALAIAPABQALgBAJgEQAIgEAHgFIAIgKIADgEIAAhUIgFgDIgPgFQgJgCgMAAQgRAAgNAIg");
	this.shape_37.setTransform(631.2,253.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_38.setTransform(611.4,259);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfAAQAJAAAIABIAOACIAFACQABgYgGgLQgFgKgRgBQgRABgOADIgTAFQgDACgCgCQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgDAMgCQANgCAPgBQAVABAMAHQALAHAFARQAEAQAAAYIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAIAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_39.setTransform(591.5,259.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUAAgZQAAgZAKgTQAJgTASgMQASgLAYgBQAOABAKACIAQAFIAGADIAAh8QAAgEACgCQACgCAEAAIAMAAQADAAADACQACACABAEIAAEVQgBADgCACQgDADgDAAIgJAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgHAGQgGAFgMAFQgLAGgPAAQgVAAgSgMgAgWAJQgMAIgHANQgGAOAAARQAAAQAGAOQAHAOALAJQAKAIAPABQAMgBAIgEQAJgEAFgFIAJgKIADgEIAAhUIgFgDIgPgFQgJgCgMAAQgRAAgMAIg");
	this.shape_40.setTransform(563.2,253.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgFCTQgEAAgCgDQgCgCAAgDIAAkVQAAgDACgCQACgDAEAAIALAAQADAAADADQACACABADIAAEVQgBADgCACQgDADgDAAg");
	this.shape_41.setTransform(549.3,253);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_42.setTransform(539,259);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgXALgVQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAVABAXQgBAYgLAUQgLAUgTAMQgSAMgYABQgXgBgSgMgAgbg0QgMAJgHANQgHAOgBAQQABAQAHAOQAHAOAMAJQAMAIAPAAQAPAAANgIQAMgJAHgOQAHgOABgQQgBgQgHgOQgHgNgMgJQgNgHgPgBQgPABgMAHg");
	this.shape_43.setTransform(520.6,259.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AA6BZQgDgBgCgBIgCgDIgzh9IgxB9IgCADQgCABgDABIgCAAQgBAAAAgBQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIgvidQgBgFABgCQACgDAEAAIANAAQADAAACACQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAfBuIAAAAIAwhzIACgDIAEgCIACAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIADADIAvBzIAAAAIAfhuQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAABAAQAAAAABAAIANAAQAFAAABADQABACgBAFIguCdQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQAAABgBAAg");
	this.shape_44.setTransform(497.8,259.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgoBMQgSgMgKgUQgKgUAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIAMANAIQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAACgEAEQgIAHgQAFQgQAHgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPANQgOANgDATIBjAAIAAAAg");
	this.shape_45.setTransform(466.3,259.3);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AA1CTQgDAAgCgDQgCgCgBgDIAAhYQAAgYgKgMQgJgMgSAAQgPAAgNAGQgLAGgHAFIgHAHIAABwQAAADgDACQgCADgDAAIgNAAQgEAAgCgDQgCgCAAgDIAAkVQAAgDACgCQACgDAEAAIANAAQADAAACADQADACAAADIAACIIAHgGQAHgFAMgFQANgGAQgBQAfABARATQARASAAAmIAABYQAAADgDACQgBADgEAAg");
	this.shape_46.setTransform(446.3,253);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgCQgCgDAAgDIAAgKQAAgDACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAADIAAAKQAAADgDADQgCACgDAAIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQgBgIgFg");
	this.shape_47.setTransform(428.6,256.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgtCPQgSgJgJgNQgIgNAAgPQAAgMAGgIQAEgIAHgFIAIgGIAAgBQgGgBgHgFQgHgEgGgIQgEgJgBgNQABgMAEgIQADgJAGgGIAJgJIAFgDIgEgFIgGgPQgDgJgBgNQABgUAIgRQAJgQAQgLQAPgKAXAAIBGAAQADAAACACQADACAAAEIAAAHIgBAFQgBAAAAABQgBAAAAAAQgBABAAAAQAAAAgBAAIgWAFIAEAFQAFAEAEALQAFAKAAARQAAATgIAQQgJAQgQAKQgQAKgUAAQgOAAgJgCQgIgDgFgCIgFgDIgEADQgEACgFAGQgEAFgBAIQAAAIAGAGQAFAGAMABIA8AAQASAAAOAFQAOAGAJAMQAIAMAAASQAAASgLAQQgMAPgTAKQgUAJgZAAQgbAAgSgIgAgaA7IgKAFQgGAEgDAGQgFAGAAAJQABAQANAJQAOAKAWAAQANAAANgFQANgFAIgIQAJgJAAgNIgCgJQgCgHgHgFQgHgGgOAAIguAAgAgghvQgLANgBAVQABAVALANQAMANAUAAQATAAAKgNQAMgNAAgVQAAgVgMgNQgKgNgTAAQgUAAgMANg");
	this.shape_48.setTransform(402.8,265.5);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_49.setTransform(382.5,259);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgFCPQgEAAgCgDQgCgCAAgDIAAiXQAAgDACgDQACgCAEAAIAMAAQADAAADACQACADAAADIAACXQAAADgCACQgDADgDAAgAgNhsQgGgFAAgJQAAgIAGgGQAGgGAHAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgHAAgGgGg");
	this.shape_50.setTransform(367.6,253.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgGCTQgDAAgCgDQgDgCAAgDIAAkVQAAgDADgCQACgDADAAIANAAQADAAACADQACACABADIAAEVQgBADgCACQgCADgDAAg");
	this.shape_51.setTransform(358.7,253);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgoBMQgSgMgKgUQgKgUAAgYQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAOAHANQAIAMANAIQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADADIADAFIAEAFIACAFQAAACgEAEQgIAHgQAFQgQAHgWABQgYgBgTgMgAAygQQgBgMgGgKQgGgKgKgHQgLgGgNgBQgUABgPANQgOANgDATIBjAAIAAAAg");
	this.shape_52.setTransform(344.7,259.3);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AAABWQgDAAgCgBIgDgDIhGieQgCgEABgCQACgDAFAAIANAAQADAAACABIACAEIA0B2IAAAAIA3h2QAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIALAAQAFAAACADQACACgCAEIhICeIgDADQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAg");
	this.shape_53.setTransform(326.4,259.5);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgZARgOQASgPAfAAQAJAAAIABIAOACIAFACQABgYgGgLQgFgKgRgBQgRABgOADIgTAFQgDACgCgCQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAIgDgLQgBgEABgCQABgCADgCIAKgDQAIgDAMgCQANgCAPgBQAVABAMAHQALAHAFARQAEAQAAAYIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgMIgMAKQgHAFgKADQgKAEgMABQgXgBgOgPgAgaAJQgLAIAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgJIAAggQgDgDgJgCQgJgCgOAAQgRAAgLAJg");
	this.shape_54.setTransform(308.4,259.3);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgsBWQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACABABADIADAMIAFgGQAGgFALgFQAKgGARAAIAPABQAHABAFADQAFADgCAGIgFAOQgCAEgDABQgCAAgDgBIgHgCQgFgCgFAAQgPABgKAGQgKAFgFAGIgEAGIAABvQgBAEgCACQgCACgDAAg");
	this.shape_55.setTransform(294.4,259);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgCQgCgDAAgDIAAgKQAAgDACgCQACgCAEgBIAVAAIAAguQAAgEADgCQACgCADAAIANgBQAEAAACACQACACAAAEIAAAvIAwAAQADABACACQADACAAADIAAAKQAAADgDADQgCACgDAAIgwAAIAABhQAAAMACAFQAEADAHAAQAIAAAJgDIANgGQAFgDACACIAEADIAGALQACADgBADQAAADgEACIgLAFQgHADgKADQgKADgKAAQgQgBgIgFg");
	this.shape_56.setTransform(278.9,256.7);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgSA6IgGgGQgBgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgDADgCIAJgJQAGgHAGgLQAEgLAAgOIgCAAIgCAAQgKAAgGgHQgHgHgBgKQABgKAHgHQAGgHAKAAQAKAAAIAIQAJAIAAAWQAAARgGAPQgGAPgIAMQgHALgHAHQgDACgDAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAAAg");
	this.shape_57.setTransform(1008.3,231.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgUQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAUABAYQgBAYgLAUQgLAUgTAMQgSAMgYAAQgXAAgSgMgAgbg0QgMAIgHAOQgHANgBARQABAQAHAPQAHAOAMAHQAMAJAPAAQAPAAANgJQAMgHAHgOQAHgPABgQQgBgRgHgNQgHgOgMgIQgNgHgPAAQgPAAgMAHg");
	this.shape_58.setTransform(993.3,221.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgiBRQgNgGgHgGIgCgDIAAgFIADgGIADgFQACgDADAAQADAAADACIAGADIAOAIQAJADAKAAQANABAHgGQAHgGAAgJQAAgKgJgIQgKgGgRgJIgWgMQgLgHgHgKQgIgLAAgOQAAgJAFgKQAGgKALgHQAMgHATgBQAQABAMAEQAMAFAGAEQADABABAFQABADgCAEIgEAGQgCAEgDABQgEABgDgCIgFgDIgNgEQgIgCgHgBQgOAAgFAGQgFAFAAAGQABAKAIAGQAJAHANAFIAbAPQAMAGAIALQAIAKAAAPQAAAMgIALQgHALgNAGQgNAHgRAAQgUAAgOgHg");
	this.shape_59.setTransform(975.9,221.2);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgUQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAUABAYQgBAYgLAUQgLAUgTAMQgSAMgYAAQgXAAgSgMgAgbg0QgMAIgHAOQgHANgBARQABAQAHAPQAHAOAMAHQAMAJAPAAQAPAAANgJQAMgHAHgOQAHgPABgQQgBgRgHgNQgHgOgMgIQgNgHgPAAQgPAAgMAHg");
	this.shape_60.setTransform(948.8,221.2);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgnCJQgRgMgKgUQgKgUgBgZQABgZAKgTQAJgTASgMQASgLAYgBQAOABAKACIAQAFIAFADIAAh8QAAgEADgCQACgCADAAIAOAAQADAAACACQACACABAEIAAEVQgBADgCACQgCADgDAAIgJAAQgBAAgBAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQgCgCgBgDIgCgLIgHAGQgGAFgMAFQgLAGgPAAQgWAAgRgMgAgXAJQgLAIgHANQgGAOAAARQAAAQAGAOQAGAOALAJQAMAIAOABQALgBAJgEQAJgEAFgFIAJgKIADgEIAAhUIgFgDIgPgFQgJgCgMAAQgRAAgNAIg");
	this.shape_61.setTransform(928,215.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgUQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAUABAYQgBAYgLAUQgLAUgTAMQgSAMgYAAQgXAAgSgMgAgbg0QgMAIgHAOQgHANgBARQABAQAHAPQAHAOAMAHQAMAJAPAAQAPAAANgJQAMgHAHgOQAHgPABgQQgBgRgHgNQgHgOgMgIQgNgHgPAAQgPAAgMAHg");
	this.shape_62.setTransform(899,221.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgDQgCgCAAgDIAAgKQAAgDACgCQACgDAEAAIAVAAIAAguQAAgDADgDQACgCADAAIANgBQAEAAACADQACABAAAEIAAAvIAwAAQADAAACADQADACAAADIAAAKQAAADgDACQgCADgDAAIgwAAIAABhQAAANACAEQAEADAHAAQAIAAAJgDIANgGQAFgCACABIAEAEIAGAKQACAEgBACQAAACgEACIgLAGQgHADgKADQgKACgKABQgQgBgIgFg");
	this.shape_63.setTransform(881.7,218.7);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AgoBMQgSgLgKgVQgKgTAAgZQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAPAHAMQAIAMANAIQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADAEIADAEIAEAFIACAFQAAACgEAEQgIAHgQAFQgQAHgWAAQgYAAgTgMgAAygQQgBgMgGgKQgGgLgKgGQgLgHgNAAQgUABgPANQgOANgDATIBjAAIAAAAg");
	this.shape_64.setTransform(855.7,221.2);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgFCTQgEAAgCgDQgCgCgBgDIAAkVQABgEACgCQACgCAEAAIALAAQAEAAACACQACACAAAEIAAEVQAAADgCACQgCADgEAAg");
	this.shape_65.setTransform(841.6,214.9);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AgaCPQgLgFgHgGIgGgFIgDALQAAADgCACQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAIgIAAQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIANAAQADAAACACQACACABAEIAAB8IAFgDIAPgFQAKgCAOgBQAZABASALQASAMAJATQAKATAAAZQAAAZgKAUQgKAUgSAMQgRAMgVAAQgPAAgMgGgAgbADIgPAFIgFADIAABUIADAEIAIAKQAGAFAJAEQAIAEAMABQAOgBALgIQALgJAHgOQAGgOAAgQQAAgRgGgOQgHgNgMgIQgMgIgRAAQgMAAgJACg");
	this.shape_66.setTransform(827.6,215.1);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgYARgOQASgQAfAAQAJgBAIACIAOACIAFACQABgYgGgKQgFgMgRAAQgRAAgOAEIgTAFQgDACgCgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIgDgLQgBgEABgCQABgCADgBIAKgEQAIgDAMgCQANgCAPgBQAVABAMAHQALAIAFAQQAEAPAAAZIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgLIgMAJQgHAFgKAEQgKADgMAAQgXAAgOgPgAgaAIQgLAJAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgIIAAgiQgDgCgJgCQgJgCgOAAQgRAAgLAIg");
	this.shape_67.setTransform(807.5,221.2);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgGCTQgDAAgCgDQgDgCAAgDIAAkVQAAgEADgCQACgCADAAIANAAQADAAACACQACACABAEIAAEVQgBADgCACQgCADgDAAg");
	this.shape_68.setTransform(794.8,214.9);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AgFCPQgEAAgCgDQgCgCAAgDIAAiXQAAgDACgDQACgCAEAAIAMAAQADAAACACQADADAAADIAACXQAAADgDACQgCADgDAAgAgOhsQgFgFAAgJQAAgIAFgGQAGgGAIAAQAIAAAGAGQAGAGAAAIQAAAJgGAFQgGAGgIAAQgIAAgGgGg");
	this.shape_69.setTransform(785.8,215.3);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgYARgOQASgQAfAAQAJgBAIACIAOACIAFACQABgYgGgKQgFgMgRAAQgRAAgOAEIgTAFQgDACgCgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIgDgLQgBgEABgCQABgCADgBIAKgEQAIgDAMgCQANgCAPgBQAVABAMAHQALAIAFAQQAEAPAAAZIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgLIgMAJQgHAFgKAEQgKADgMAAQgXAAgOgPgAgaAIQgLAJAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgIIAAgiQgDgCgJgCQgJgCgOAAQgRAAgLAIg");
	this.shape_70.setTransform(772,221.2);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AAABWQgDAAgCgBIgDgDIhGieQgCgEABgCQACgDAFAAIANAAQADAAACABIACAEIA0B2IAAAAIA3h2QAAgBABAAQAAgBAAAAQABgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIALAAQAFAAACADQACACgCAEIhICeIgDADQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAg");
	this.shape_71.setTransform(755.1,221.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgYARgOQASgQAfAAQAJgBAIACIAOACIAFACQABgYgGgKQgFgMgRAAQgRAAgOAEIgTAFQgDACgCgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIgDgLQgBgEABgCQABgCADgBIAKgEQAIgDAMgCQANgCAPgBQAVABAMAHQALAIAFAQQAEAPAAAZIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgLIgMAJQgHAFgKAEQgKADgMAAQgXAAgOgPgAgaAIQgLAJAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgIIAAgiQgDgCgJgCQgJgCgOAAQgRAAgLAIg");
	this.shape_72.setTransform(737.1,221.2);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AgiBRQgNgGgHgGIgCgDIAAgFIADgGIADgFQACgDADAAQADAAADACIAGADIAOAIQAJADAKAAQANABAHgGQAHgGAAgJQAAgKgJgIQgKgGgRgJIgWgMQgLgHgHgKQgIgLAAgOQAAgJAFgKQAGgKALgHQAMgHATgBQAQABAMAEQAMAFAGAEQADABABAFQABADgCAEIgEAGQgCAEgDABQgEABgDgCIgFgDIgNgEQgIgCgHgBQgOAAgFAGQgFAFAAAGQABAKAIAGQAJAHANAFIAbAPQAMAGAIALQAIAKAAAPQAAAMgIALQgHALgNAGQgNAHgRAAQgUAAgOgHg");
	this.shape_73.setTransform(712.3,221.2);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AgFCPQgEAAgBgDQgDgCAAgDIAAiXQAAgDADgDQABgCAEAAIAMAAQADAAACACQACADABADIAACXQgBADgCACQgCADgDAAgAgOhsQgFgFAAgJQAAgIAFgGQAGgGAIAAQAJAAAFAGQAGAGAAAIQAAAJgGAFQgFAGgJAAQgIAAgGgGg");
	this.shape_74.setTransform(700.2,215.3);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("Ag7CTQgFgBgCgCQgCgDACgFIA2hzIhOieQgCgEABgDQACgCAFAAIATAAIAEABQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABIA+CAIAAAAIA7iAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABgBQAAAAABAAQABAAAAAAIAQAAQAFAAACADQABADgCADIiAEXIgDADQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_75.setTransform(676.6,227.5);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgtCPQgSgJgJgNQgIgNAAgPQAAgMAGgIQAFgIAFgFIAJgGIAAgBQgGgBgHgFQgHgEgGgIQgEgJgBgNQABgMADgIQAEgJAGgGIAJgJIAFgDIgEgFIgGgPQgDgJgBgNQABgUAIgRQAJgQAQgLQAPgKAXAAIBGAAQADAAADACQACACAAAEIAAAHIgBAFQgBAAAAABQgBAAAAAAQgBABAAAAQAAAAgBAAIgWAFIAEAFQAFAEAEALQAFAKAAARQAAATgIAQQgJAQgQAKQgPAKgVAAQgOAAgIgCQgKgDgEgCIgEgDIgFADQgFACgEAGQgFAFAAAIQAAAIAGAGQAFAGAMABIA8AAQASAAAOAFQAOAGAJAMQAIAMAAASQAAASgLAQQgMAPgTAKQgTAJgaAAQgbAAgSgIgAgaA7IgKAFQgGAEgDAGQgFAGAAAJQAAAQAOAJQAOAKAWAAQANAAANgFQANgFAIgIQAJgJAAgNIgCgJQgCgHgHgFQgHgGgOAAIguAAgAgfhvQgMANgBAVQABAVAMANQALANAUAAQATAAAKgNQAMgNAAgVQAAgVgMgNQgKgNgTAAQgUAAgLANg");
	this.shape_76.setTransform(657.6,227.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgUQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAUABAYQgBAYgLAUQgLAUgTAMQgSAMgYAAQgXAAgSgMgAgbg0QgMAIgHAOQgHANgBARQABAQAHAPQAHAOAMAHQAMAJAPAAQAPAAANgJQAMgHAHgOQAHgPABgQQgBgRgHgNQgHgOgMgIQgNgHgPAAQgPAAgMAHg");
	this.shape_77.setTransform(637.5,221.2);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgFCTQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIALAAQAEAAACACQACACAAAEIAAEVQAAADgCACQgCADgEAAg");
	this.shape_78.setTransform(622.9,214.9);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgUQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAUABAYQgBAYgLAUQgLAUgTAMQgSAMgYAAQgXAAgSgMgAgbg0QgMAIgHAOQgHANgBARQABAQAHAPQAHAOAMAHQAMAJAPAAQAPAAANgJQAMgHAHgOQAHgPABgQQgBgRgHgNQgHgOgMgIQgNgHgPAAQgPAAgMAHg");
	this.shape_79.setTransform(608.3,221.2);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_80.setTransform(587.9,221);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AA1CTQgCAAgDgDQgCgCgBgDIAAhYQABgYgLgMQgJgMgSAAQgPAAgMAGQgNAFgGAHIgHAFIAABxQgBADgBACQgDADgDAAIgNAAQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIANAAQADAAADACQABACABAEIAACIIAHgGQAGgFANgGQANgFAQgBQAgABAQATQARATAAAlIAABYQAAADgDACQgCADgDAAg");
	this.shape_81.setTransform(567.1,214.9);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AgfBNQgUgMgMgUQgLgTgBgaQABgYAMgUQAMgTATgMQAUgMAWgBQATAAAPAIQAPAHALAPQACADAAADQgBADgDADIgIAHQgEAEgDgCIgFgEQgGgHgKgGQgKgEgNgBQgOAAgNAIQgNAIgHAOQgHANAAAQQAAARAHAOQAHAOANAHQAMAJAPAAQASgBAKgHQAKgHAGgHQAEgEADAAQADAAADADIAFAEQADABABADQABAEgCADQgKAPgQALQgRAJgWAAQgWAAgTgLg");
	this.shape_82.setTransform(547.3,221.2);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AgoBMQgSgLgKgVQgKgTAAgZQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAPAHAMQAIAMANAIQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADAEIADAEIAEAFIACAFQAAACgEAEQgIAHgQAFQgQAHgWAAQgYAAgTgMgAAygQQgBgMgGgKQgGgLgKgGQgLgHgNAAQgUABgPANQgOANgDATIBjAAIAAAAg");
	this.shape_83.setTransform(528.5,221.2);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgDQgCgCAAgDIAAgKQAAgDACgCQACgDAEAAIAVAAIAAguQAAgDADgDQACgCADAAIANgBQAEAAACADQACABAAAEIAAAvIAwAAQADAAACADQADACAAADIAAAKQAAADgDACQgCADgDAAIgwAAIAABhQAAANACAEQAEADAHAAQAIAAAJgDIANgGQAFgCACABIAEAEIAGAKQACAEgBACQAAACgEACIgLAGQgHADgKADQgKACgKABQgQgBgIgFg");
	this.shape_84.setTransform(511.6,218.7);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AgoBMQgSgLgKgVQgKgTAAgZQAAgXAKgUQAKgUASgMQATgMAYgBQAWABARAKQASAKAJARQAKARAAAXIAAAFIgBAFQAAADgCACQgCACgDAAIh4AAQABAPAHAMQAIAMANAIQAMAHAOABQAOgBAKgDQAKgEAIgFIAHgDQACgBADAEIADAEIAEAFIACAFQAAACgEAEQgIAHgQAFQgQAHgWAAQgYAAgTgMgAAygQQgBgMgGgKQgGgLgKgGQgLgHgNAAQgUABgPANQgOANgDATIBjAAIAAAAg");
	this.shape_85.setTransform(485.6,221.2);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AA1CTQgDAAgCgDQgCgCgBgDIAAhYQAAgYgKgMQgJgMgSAAQgPAAgNAGQgMAFgHAHIgGAFIAABxQAAADgDACQgCADgDAAIgNAAQgEAAgCgDQgCgCAAgDIAAkVQAAgEACgCQACgCAEAAIANAAQADAAACACQADACAAAEIAACIIAGgGQAHgFANgGQANgFAQgBQAfABARATQARATAAAlIAABYQAAADgDACQgBADgEAAg");
	this.shape_86.setTransform(465.7,214.9);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AgQBsQgJgHgCgKQgDgKAAgOIAAhjIgVAAQgEAAgCgDQgCgCAAgDIAAgKQAAgDACgCQACgDAEAAIAVAAIAAguQAAgDADgDQACgCADAAIANgBQAEAAACADQACABAAAEIAAAvIAwAAQADAAACADQADACAAADIAAAKQAAADgDACQgCADgDAAIgwAAIAABhQAAANACAEQAEADAHAAQAIAAAJgDIANgGQAFgCACABIAEAEIAGAKQACAEgBACQAAACgEACIgLAGQgHADgKADQgKACgKABQgQgBgIgFg");
	this.shape_87.setTransform(447.9,218.7);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AgiBRQgNgGgHgGIgCgDIAAgFIADgGIADgFQACgDADAAQADAAADACIAGADIAOAIQAJADAKAAQANABAHgGQAHgGAAgJQAAgKgJgIQgKgGgRgJIgWgMQgLgHgHgKQgIgLAAgOQAAgJAFgKQAGgKALgHQAMgHATgBQAQABAMAEQAMAFAGAEQADABABAFQABADgCAEIgEAGQgCAEgDABQgEABgDgCIgFgDIgNgEQgIgCgHgBQgOAAgFAGQgFAFAAAGQABAKAIAGQAJAHANAFIAbAPQAMAGAIALQAIAKAAAPQAAAMgIALQgHALgNAGQgNAHgRAAQgUAAgOgHg");
	this.shape_88.setTransform(424.2,221.2);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("AgxBJQgPgOAAgZIAAgBQAAgYARgOQASgQAfAAQAJgBAIACIAOACIAFACQABgYgGgKQgFgMgRAAQgRAAgOAEIgTAFQgDACgCgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIgDgLQgBgEABgCQABgCADgBIAKgEQAIgDAMgCQANgCAPgBQAVABAMAHQALAIAFAQQAEAPAAAZIAABcQAAADgCACQgDADgDAAIgIAAQgDAAgCgCIgCgEIgDgLIgMAJQgHAFgKAEQgKADgMAAQgXAAgOgPgAgaAIQgLAJAAAQIAAABQAAANAIAHQAIAJANAAQAPAAANgIQAMgHAFgIIAAgiQgDgCgJgCQgJgCgOAAQgRAAgLAIg");
	this.shape_89.setTransform(407.1,221.2);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AgtCPQgSgJgJgNQgHgNAAgPQAAgMAEgIQAFgIAGgFIAIgGIAAgBQgFgBgHgFQgHgEgGgIQgFgJAAgNQAAgMAEgIQAEgJAGgGIAJgJIAFgDIgDgFIgHgPQgDgJgBgNQABgUAIgRQAJgQAQgLQAQgKAVAAIBGAAQAEAAADACQABACAAAEIAAAHIgBAFQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIgXAFIAFAFQAFAEAFALQAEAKAAARQAAATgJAQQgIAQgQAKQgPAKgWAAQgNAAgIgCQgKgDgEgCIgEgDIgFADQgEACgFAGQgEAFgBAIQAAAIAGAGQAGAGALABIA8AAQARAAAPAFQAOAGAIAMQAJAMAAASQAAASgLAQQgLAPgUAKQgTAJgaAAQgbAAgSgIgAgaA7IgKAFQgGAEgEAGQgEAGAAAJQAAAQAOAJQAOAKAWAAQANAAANgFQANgFAJgIQAHgJABgNIgCgJQgCgHgHgFQgGgGgPAAIguAAgAgfhvQgNANAAAVQAAAVANANQALANAUAAQASAAAMgNQALgNAAgVQAAgVgLgNQgMgNgSAAQgUAAgLANg");
	this.shape_90.setTransform(380.3,227.5);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AA1BWQgDAAgCgCQgCgCgBgEIAAhXQAAgYgKgMQgJgMgSAAQgPAAgMAGQgMAGgHAGIgHAGIAABvQgBAEgCACQgCACgDAAIgNAAQgEAAgCgCQgCgCAAgEIAAiXQAAgDACgCQACgDAEAAIAIAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIAEANIAIgGQAHgFANgFQANgGARAAQAYAAAOAKQAPAJAGARQAGASAAAWIAABXQAAAEgDACQgCACgDAAg");
	this.shape_91.setTransform(360,221);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("AgpBMQgTgMgLgUQgLgUgBgYQABgYALgUQALgTATgMQASgMAXgBQAYABASAMQATAMALATQALAUABAYQgBAYgLAUQgLAUgTAMQgSAMgYAAQgXAAgSgMgAgbg0QgMAIgHAOQgHANgBARQABAQAHAPQAHAOAMAHQAMAJAPAAQAPAAANgJQAMgHAHgOQAHgPABgQQgBgRgHgNQgHgOgMgIQgNgHgPAAQgPAAgMAHg");
	this.shape_92.setTransform(339.3,221.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#000000").s().p("AgGCTQgDAAgCgDQgCgCgBgDIAAkVQABgEACgCQACgCADAAIANAAQACAAADACQACACAAAEIAAEVQAAADgCACQgDADgCAAg");
	this.shape_93.setTransform(324.8,214.9);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#000000").s().p("AgiBRQgNgGgHgGIgCgDIAAgFIADgGIADgFQACgDADAAQADAAADACIAGADIAOAIQAJADAKAAQANABAHgGQAHgGAAgJQAAgKgJgIQgKgGgRgJIgWgMQgLgHgHgKQgIgLAAgOQAAgJAFgKQAGgKALgHQAMgHATgBQAQABAMAEQAMAFAGAEQADABABAFQABADgCAEIgEAGQgCAEgDABQgEABgDgCIgFgDIgNgEQgIgCgHgBQgOAAgFAGQgFAFAAAGQABAKAIAGQAJAHANAFIAbAPQAMAGAIALQAIAKAAAPQAAAMgIALQgHALgNAGQgNAHgRAAQgUAAgOgHg");
	this.shape_94.setTransform(303.7,221.2);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#000000").s().p("ABwCVQAAAAgBAAQAAAAgBAAQgBAAAAgBQgBAAAAAAIgDgDIgfhGIiUAAIgfBGIgCADQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAgBAAIgRAAQgEAAgCgDQgCgDABgFICAkZIADgEQAAAAABAAQAAgBABAAQAAAAABAAQABAAAAAAIADAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAAAABQAAAAAAABIB/EZQACAFgCADQgCADgFAAgAA/AxIgfhEIgfhFIgCAAIg9CJIB9AAIAAAAg");
	this.shape_95.setTransform(282.1,214.7);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#000000").s().p("AguAvQgSgSgBgdQABgaASgUQATgSAbgBQAbABAUASQASAUABAaQgBAdgSASQgUASgbABQgbgBgTgSg");
	this.shape_96.setTransform(787.4,162.6);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#000000").s().p("AhYEFQgjgWgUgnQgUglAAgvQAAgvAUgnQATgkAkgWQAkgWAwgBQAXABARAEQATAFALAFIAAjoQAAgGAEgEQAEgFAHAAIBEAAQAGAAAEAFQAEAEABAGIAAIRQgBAGgEAEQgEAEgGABIggAAQgFAAgEgFQgEgDgCgHIgHgZQAAACgNALQgMALgXALQgYANghAAQgrAAgjgXgAgwA6QgWAYAAAiQAAAjAUAWQAUAYAgABQAUAAAOgJQAOgJAIgMQAIgMACgLIAAhcIgHgFQgHgFgOgEQgNgFgVAAQghABgVAXg");
	this.shape_97.setTransform(756.8,140.8);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#000000").s().p("AggEYQgHgBgEgEQgEgEgBgGIAAoRQABgGAEgEQAEgFAHAAIBCAAQAGAAAEAFQAFAEAAAGIAAIRQAAAGgFAEQgEAEgGABg");
	this.shape_98.setTransform(728.3,140.4);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#000000").s().p("AhgCkQgHgBgEgEQgEgEgBgGIAAkgQABgIAEgDQAEgFAHAAIAeAAQAFAAAEADQAEACABAFIALAgQAGgJAMgMQAMgLARgJQASgIAZgBQATAAAQAEQAPADAIAIQAIAHgEAKIgeA0QgDAFgFACQgGACgEgCIgKgDIgOgCQgQAAgLAGQgMAGgGAIQgIAHgCAGIAADBQAAAIgFADQgFAEgJAAg");
	this.shape_99.setTransform(707.4,152);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#000000").s().p("AhSCRQglgXgWgmQgVgmgBguQABgtAVgnQAWglAlgWQAlgXAtgBQAuABAlAXQAlAWAWAlQAWAnAAAtQAAAugWAmQgWAmglAXQglAXguAAQgtAAglgXgAg1g5QgWAXgBAiQABAjAWAWQAVAYAgABQAhgBAVgYQAWgWABgjQgBgigWgXQgVgXghgBQggABgVAXg");
	this.shape_100.setTransform(672.6,152.4);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#000000").s().p("AByCoQgFAAgDgCIgFgFIhli6IAAAAIhjC6IgFAFQgEACgEAAIgEAAQgGAAgDgDQgEgCgBgEIhkksQgDgHAEgFQAEgGAJAAIA5AAQAEAAAFADQAEADACADIAwCQIAAAAIABAAIBRiaQABgCAEgDQADgCAFAAIAFAAQAGAAADACIAEAFIBRCaIABAAIAwiPQACgHAFgCQAFgBAGAAIA0AAQAJAAAEAGQAEAFgCAHIhkEsQgBAEgEACQgEADgGAAg");
	this.shape_101.setTransform(629.2,152.4);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#000000").s().p("AhNCRQgkgWgVgnQgVglAAgvQAAgtAVglQAVgnAkgWQAlgXAvgBQAqABAhASQAiATAUAiQAUAhAAAsIAAALIgBAJQgBAGgEAEQgEAEgGAAIjMAAQABAQAKAQQAJAQARALQARAKAWABQATgBAQgFQAQgHALgHQAGgEAFAAQAGgBAEAFIAhAlQAEAFABAFQAAAHgGAEQgUATgeAMQgeANgnAAQgvAAgmgXgAA/gnQgCgXgRgQQgQgPgXgBQgYAAgRAQQgRAPgEAYIB4AAIAAAAg");
	this.shape_102.setTransform(569.4,152.4);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#000000").s().p("ABTEYQgGgBgFgEQgEgEAAgGIAAibQAAghgRgTQgRgUgdAAQgbAAgSAQQgSAQgGAZIAACqQAAAHgEADQgEAFgJAAIhCAAQgGgBgFgEQgEgEAAgGIAAoRQAAgGAEgEQAFgFAGAAIBEAAQAGAAAFAFQAEAEAAAGIAADzQAMgKAXgIQAVgHAcgBQAzABAfAXQAgAWAPAjQAOAkAAApIAACaQAAAGgEAEQgFAEgGABg");
	this.shape_103.setTransform(530.9,140.4);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#000000").s().p("Ag2C9QgVgbAAgxIAAiMIgbAAQgHAAgEgEQgEgFAAgGIAAg1QAAgHAEgEQAEgFAHAAIAbAAIAAhYQAAgHAEgEQAFgEAGgBIBAAAQAHAAAEAEQAEAFAAAGIAABZIBGAAQAHAAAEAFQAEAEAAAHIAAA1QAAAGgEAFQgEAEgHAAIhGAAIAAB/QAAARAHAFQAIAFAKgBQAKAAALgDIASgGQAHgCAEADQAFACACAGIAQAzQACAFgDAGQgCAFgGADIgSAGQgPAFgVAFQgVAEgVAAQgsAAgWgbg");
	this.shape_104.setTransform(496.3,147.6);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#000000").s().p("ABSCkQgGAAgFgEQgFgFAAgGIAAieQAAgfgPgTQgPgRgdgBQgUABgPAHQgQAIgJAMQgKAMgFALIAACvQAAAIgDAEQgGADgLAAIg6AAQgHAAgFgEQgEgFAAgGIAAkhQAAgGAEgEQAFgFAHAAIAeAAQAFAAAEADQACADACAEIAMAdQAFgHAPgLQAPgLAXgIQAYgKAdAAQAzAAAfAWQAgAXAOAkQAPAjAAArIAACZQgBAGgEAFQgEAEgHAAg");
	this.shape_105.setTransform(992.2,69.6);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#000000").s().p("AggEQQgGAAgEgEQgEgFgBgGIAAkhQABgGAEgEQAEgFAGAAIBBAAQAHAAAEAFQAEAEABAGIAAEhQgBAGgEAFQgEAEgHAAgAgnixQgPgQAAgXQAAgXAPgQQAQgQAXAAQAXAAAQAQQAQAQAAAXQAAAXgQAQQgQAQgXABQgXgBgQgQg");
	this.shape_106.setTransform(961.4,58.8);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#000000").s().p("AhNCRQgkgXgVglQgVgnAAguQAAgtAVgmQAVgmAkgXQAlgWAvgBQAqAAAhAUQAiASAUAiQAUAhAAArIAAALIgBAKQgBAGgEAEQgEAEgGAAIjMAAQABAQAKARQAJAPARALQARAKAWABQATAAAQgHQAQgFALgIQAGgEAFgBQAGAAAEAFIAhAmQAEADABAHQAAAFgGAFQgUATgeANQgeAMgnAAQgvAAgmgXgAA/gnQgCgXgRgPQgQgQgXAAQgYgBgRARQgRAPgEAXIB4AAIAAAAg");
	this.shape_107.setTransform(916.5,70);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#000000").s().p("AhgCkQgHAAgEgEQgEgFgBgGIAAkhQABgGAEgEQAEgFAHAAIAeAAQAFAAAEADQAEADABAEIALAfQAGgIAMgLQAMgMARgIQASgKAZAAQATAAAQAEQAPAEAIAGQAIAIgEAKIgeA0QgDAGgFACQgGABgEgCIgKgDIgOgCQgQABgLAFQgMAGgGAHQgIAIgCAGIAADBQAAAIgFAEQgFADgJAAg");
	this.shape_108.setTransform(887.3,69.6);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#000000").s().p("AhNCRQgkgXgVglQgVgnAAguQAAgtAVgmQAVgmAkgXQAlgWAvgBQAqAAAhAUQAiASAUAiQAUAhAAArIAAALIgBAKQgBAGgEAEQgEAEgGAAIjMAAQABAQAKARQAJAPARALQARAKAWABQATAAAQgHQAQgFALgIQAGgEAFgBQAGAAAEAFIAhAmQAEADABAHQAAAFgGAFQgUATgeANQgeAMgnAAQgvAAgmgXgAA/gnQgCgXgRgPQgQgQgXAAQgYgBgRARQgRAPgEAXIB4AAIAAAAg");
	this.shape_109.setTransform(853.6,70);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#000000").s().p("ABTEYQgGAAgFgEQgEgFAAgGIAAibQAAghgRgUQgRgSgdgBQgbABgSAPQgSAQgGAZIAACqQAAAGgEAFQgEAEgJAAIhCAAQgGAAgFgEQgEgFAAgGIAAoRQAAgGAEgFQAFgEAGAAIBEAAQAGAAAFAEQAEAFAAAGIAAD0QAMgLAXgHQAVgJAcAAQAzABAfAWQAgAXAPAjQAOAkAAApIAACaQAAAGgEAFQgFAEgGAAg");
	this.shape_110.setTransform(815.1,58);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#000000").s().p("AByCoQgFAAgDgBIgFgGIhli6IAAAAIhjC6IgFAGQgEABgEAAIgEAAQgGAAgDgCQgEgDgBgEIhkkrQgDgJAEgFQAEgEAJgBIA5AAQAEAAAFADQAEADACAEIAwCPIAAAAIABAAIBRiaQABgCAEgDQADgCAFAAIAFAAQAGAAADACIAEAFIBRCaIABAAIAwiPQACgHAFgBQAFgCAGAAIA0AAQAJABAEAEQAEAFgCAJIhkErQgBAEgEADQgEACgGAAg");
	this.shape_111.setTransform(769.3,70);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#000000").s().p("AiUEYQgJAAgEgHQgEgGAEgJIBxjwIiCkUQgDgIAEgHQAEgFAJgBIBIAAQAFAAAEADQADACABAEIBQC1IABAAIBQi1QADgGAEgBQAFgCAHAAIBAAAQAKABAEAFQAEAHgEAIIj0IQQgCAEgDACQgEAEgFAAg");
	this.shape_112.setTransform(726.2,82);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#000000").s().p("ABSCkQgHAAgEgEQgFgFABgGIAAieQgBgfgPgTQgPgRgdgBQgUABgPAHQgQAIgKAMQgKAMgDALIAACvQgBAIgEAEQgEADgMAAIg6AAQgHAAgEgEQgFgFAAgGIAAkhQAAgGAFgEQAEgFAHAAIAeAAQAFAAADADQADADADAEIALAdQAFgHAPgLQAQgLAWgIQAYgKAdAAQAzAAAgAWQAfAXAPAkQAOAjAAArIAACZQgBAGgEAFQgEAEgGAAg");
	this.shape_113.setTransform(687.3,69.6);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#000000").s().p("AhpCLQgdgdgBgzQAAgsAhgbQAhgcA9gBQAYAAARAEIARAFQABgfgKgMQgKgNgXAAQgOAAgRACQgRABgPADQgQADgJAEQgIABgFgEQgEgEgCgIIgHgqQgBgJADgFQAEgEAFgCIAUgFQAQgEAYgDQAXgCAZgBQAyAAAbAQQAaARALAgQAKAfgBArIAACtQAAAGgEAFQgFAEgGAAIgdAAQgEAAgDgCQgDgCgDgHIgKgWQgNAOgYANQgXANgkABQgxAAgdgdgAghAbQgOAMAAAUQAAASALALQALAMATAAQAMAAAMgFQALgHAJgHQAIgHADgFIAAgsIgOgFQgNgFgSAAQgXAAgOAMg");
	this.shape_114.setTransform(648.2,70);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#000000").s().p("AC7CkQgHAAgEgEQgFgFAAgGIAAieQAAgfgOgTQgQgRgegBQgXABgPAIQgPAIgHAIIgHAJIABAKIAAAUIAACiQAAAGgFAFQgEAEgGAAIg7AAQgHAAgEgEQgEgFAAgGIAAieQAAgfgPgTQgOgRgfgBQgUABgNAHQgOAIgIAMQgIAMgEALIAACvQAAAGgFAFQgEAEgGAAIhBAAQgGAAgFgEQgEgFAAgGIAAkhQAAgGAEgEQAFgFAGAAIAeAAQAFAAAEADQADACABADIALAfQAHgIAPgLQAOgLAWgIQAVgJAdAAQAiAAAZANQAZAMATAYQAHgHAPgLQAQgNAXgIQAXgKAdAAQAzAAAfAWQAeAXAOAkQAOAkAAArIAACYQAAAGgFAFQgEAEgGAAg");
	this.shape_115.setTransform(583.6,69.6);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#000000").s().p("AhSCRQglgXgWgmQgVgmgBguQABguAVglQAWgmAlgXQAlgWAtgBQAuABAlAWQAlAXAWAmQAWAlAAAuQAAAugWAmQgWAmglAXQglAXguAAQgtAAglgXgAg1g5QgWAWgBAjQABAiAWAYQAVAXAgABQAhgBAVgXQAWgYABgiQgBgjgWgWQgVgXghgBQggABgVAXg");
	this.shape_116.setTransform(533.3,70);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#000000").s().p("AhgCkQgHAAgEgEQgEgFgBgGIAAkhQABgGAEgEQAEgFAHAAIAeAAQAFAAAEADQAEADABAEIALAfQAGgIAMgLQAMgMARgIQASgKAZAAQATAAAQAEQAPAEAIAGQAIAIgEAKIgeA0QgDAGgFACQgGABgEgCIgKgDIgOgCQgQABgLAFQgMAGgGAHQgIAIgCAGIAADBQAAAIgFAEQgFADgJAAg");
	this.shape_117.setTransform(503.4,69.6);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#000000").s().p("AhXEcQgHAAgEgEQgEgFgBgGIAAjdIgbAAQgHAAgDgEQgFgFAAgGIAAg0QAAgHAFgEQADgFAHAAIAbAAIAAhWQABg2ATgjQAUgkAhgTQAhgSArAAQAgABAaAKQAZAKAMAKQADADABAGQABAFgCAFIgcAzQgCAEgGACQgFABgGgDQgIgFgNgGQgMgFgOAAQgaAAgNATQgOASAAAkIAABWIBQAAQAGAAAEAFQAEAEABAHIAAA0QgBAGgEAFQgEAEgGAAIhQAAIAADdQAAAGgEAFQgFAEgGAAg");
	this.shape_118.setTransform(476.9,57.6);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#000000").s().p("ABFEYQgEAAgEgCIgGgEIh9iRIAACIQgBAGgEAFQgEAEgGAAIhEAAQgHAAgEgEQgEgFgBgGIAAoRQABgGAEgFQAEgEAHAAIBEAAQAGAAAEAEQAEAFABAGIAAFaIBthvIAJgHQAFgDAGAAIBJAAQAKABADAHQADAIgGAHIh3B5ICOCZQAGAHgCAHQgEAHgKABg");
	this.shape_119.setTransform(424.8,58);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#000000").s().p("AhgCkQgHAAgEgEQgEgFgBgGIAAkhQABgGAEgEQAEgFAHAAIAeAAQAFAAAEADQAEADABAEIALAfQAGgIAMgLQAMgMARgIQASgKAZAAQATAAAQAEQAPAEAIAGQAIAIgEAKIgeA0QgDAGgFACQgGABgEgCIgKgDIgOgCQgQABgLAFQgMAGgGAHQgIAIgCAGIAADBQAAAIgFAEQgFADgJAAg");
	this.shape_120.setTransform(391.8,69.6);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#000000").s().p("AhSCRQglgXgWgmQgVgmgBguQABguAVglQAWgmAlgXQAlgWAtgBQAuABAlAWQAlAXAWAmQAWAlAAAuQAAAugWAmQgWAmglAXQglAXguAAQgtAAglgXgAg1g5QgWAWgBAjQABAiAWAYQAVAXAgABQAhgBAVgXQAWgYABgiQgBgjgWgWQgVgXghgBQggABgVAXg");
	this.shape_121.setTransform(357,70);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#000000").s().p("ACeEgQgGAAgDgCQgEgDgBgEIiPlpIgDAAIiOFpQgBAEgDADQgDACgGAAIgNAAQgFAAgEgDQgEgDgCgFIiXoZQgCgIAEgFQAEgGAJAAIBKAAQAEAAAFAEQADADACAEIBTE/IADAAIB/lJQABgEAEgCQADgDAGAAIANAAQAGAAAEADQADACABAEICAFJIADAAIBSk/QABgEAEgDQAEgEAFAAIBKAAQAIAAAEAGQAFAFgDAIIiXIZQgBAFgEADQgFADgEAAg");
	this.shape_122.setTransform(302.3,58);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.TextBoi, new cjs.Rectangle(0,0,1281.4,323.7), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Az1JWIAAyrMAnqAAAIAASrg");
	this.shape.setTransform(127,59.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,0,253.9,119.5), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.fern();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,185,402), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Groundsand();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,1280,1024), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.laptop();
	this.instance.parent = this;
	this.instance.setTransform(0,0,2.534,2.534);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,1163.1,575.2), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Groundwork();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,1280,1024), null);


(lib.returnbutton_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.returnbutton();
	this.instance.parent = this;

	this.instance_1 = new lib.returnbuttonhover();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,230,95);


// stage content:
(lib.Untitled2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var aOfficeNoise = new Audio('sounds/roomNoise.mp3');
		var aClick = new Audio('sounds/click.mp3');
		aOfficeNoise.play();
		
		this.backToMain.addEventListener("click", buttonClicked.bind(this));
		
		function buttonClicked()
		{
			//this.play();
			aClick.play();
			if (this.currentFrame < 100) {
				//Inside baby
				localStorage.setItem("15018394-background","room");
			} else {
				//Outside baby
				localStorage.setItem("15018394-background","beach");
			}
			
			window.open("index.html","_self");
		}
		console.log(localStorage.getItem("background"));
	}
	this.frame_169 = function() {
		this.gotoAndPlay(43);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(169).call(this.frame_169).wait(1));

	// Layer 6
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(635.1,958.7,1,1,0,0,0,127,59.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:0.917},0).wait(1).to({alpha:0.833},0).wait(1).to({alpha:0.75},0).wait(1).to({alpha:0.667},0).wait(1).to({alpha:0.583},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.417},0).wait(1).to({alpha:0.333},0).wait(1).to({alpha:0.25},0).wait(1).to({alpha:0.167},0).wait(1).to({alpha:0.083},0).wait(1).to({alpha:0},0).to({_off:true},1).wait(157));

	// Layer 8
	this.backToMain = new lib.returnbutton_1();
	this.backToMain.parent = this;
	this.backToMain.setTransform(647,970.9,1,1,0,0,0,115,47.5);
	new cjs.ButtonHelper(this.backToMain, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.backToMain).wait(170));

	// Layer 4
	this.instance_1 = new lib.TextBoi();
	this.instance_1.parent = this;
	this.instance_1.setTransform(1990.7,229.9,1,1,0,0,0,640.7,161.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(13).to({_off:false},0).wait(1).to({regX:639.6,regY:173.7,x:1823.8,y:241.8},0).wait(1).to({x:1663},0).wait(1).to({x:1507.1},0).wait(1).to({x:1355.9},0).wait(1).to({x:1209.5},0).wait(1).to({x:1067.6},0).wait(1).to({x:930.1},0).wait(1).to({x:796.9},0).wait(1).to({x:667.9},0).wait(1).to({x:642.1},0).wait(147));

	// Layer 1
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(1931.5,696.6,1,1,0,0,0,581.5,287.6);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(17).to({_off:false},0).wait(1).to({x:1804.1},0).wait(1).to({x:1680.7},0).wait(1).to({x:1561.2},0).wait(1).to({x:1445.4},0).wait(1).to({x:1333.3},0).wait(1).to({x:1224.7},0).wait(1).to({x:1119.7},0).wait(1).to({x:1018},0).wait(1).to({x:919.6},0).wait(1).to({x:824.3},0).wait(1).to({x:732.2},0).wait(1).to({x:643},0).wait(1).to({x:585.5},0).wait(140));

	// Layer 5
	this.instance_3 = new lib.Symbol4();
	this.instance_3.parent = this;
	this.instance_3.setTransform(1946.5,656,1,1,0,0,0,640,512);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(109).to({_off:false},0).wait(1).to({x:1741.1},0).wait(1).to({x:1558.8},0).wait(1).to({x:1397.2},0).wait(1).to({x:1254.2},0).wait(1).to({x:1127.8},0).wait(1).to({x:1015.9},0).wait(1).to({x:916.8},0).wait(1).to({x:828.7},0).wait(1).to({x:750.3},0).wait(1).to({x:679.7},0).wait(1).to({x:640},0).wait(24).to({x:602.6},0).wait(1).to({x:450.1},0).wait(1).to({x:277.7},0).wait(1).to({x:82.6},0).wait(1).to({x:-137.7},0).wait(1).to({x:-386.3},0).wait(1).to({x:-666.5},0).to({_off:true},1).wait(19));

	// Fern
	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(1576.5,724,1,1,0,0,0,92.5,201);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(46).to({_off:false},0).wait(1).to({x:1434.4},0).wait(1).to({x:1292.3},0).wait(1).to({x:1150.2},0).wait(1).to({x:1008.1},0).wait(1).to({x:866},0).wait(1).to({x:723.9},0).wait(1).to({x:581.8},0).wait(1).to({x:439.7},0).wait(1).to({x:297.6},0).wait(1).to({x:155.5},0).wait(28).to({x:98.3},0).wait(1).to({x:41.2},0).wait(1).to({x:-16},0).wait(1).to({x:-73.1},0).wait(1).to({x:-130.3},0).wait(1).to({x:-187.5},0).to({_off:true},1).wait(80));

	// Layer 3
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(1991,647,1,1,0,0,0,640,512);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(43).to({_off:false},0).wait(1).to({x:1803},0).wait(1).to({x:1635.1},0).wait(1).to({x:1485.5},0).wait(1).to({x:1352.3},0).wait(1).to({x:1233.8},0).wait(1).to({x:1128.4},0).wait(1).to({x:1034.6},0).wait(1).to({x:950.9},0).wait(1).to({x:876},0).wait(1).to({x:808.4},0).wait(1).to({x:747.4},0).wait(1).to({x:691.5},0).wait(1).to({x:640.1},0).wait(1).to({x:639.3},0).wait(1).to({x:639.5},0).wait(1).to({x:639.7},0).wait(1).to({x:639.9},0).wait(1).to({x:640},0).wait(1).to({x:640.2},0).wait(1).to({x:640.3},0).wait(1).to({x:640.5},0).wait(1).to({x:640.7},0).wait(1).to({x:640.8},0).wait(1).to({x:641},0).wait(1).to({x:641.2},0).wait(1).to({x:641.4},0).wait(1).to({x:641.5},0).wait(1).to({x:641.7},0).wait(1).to({x:641.9},0).wait(1).to({x:642.1},0).wait(1).to({x:642.4},0).wait(1).to({x:642.6},0).wait(1).to({x:642.9},0).wait(1).to({x:643.1},0).wait(1).to({x:643.5},0).wait(1).to({x:539.9},0).wait(1).to({x:414.3},0).wait(1).to({x:273.1},0).wait(1).to({x:114.5},0).wait(1).to({x:-63.9},0).wait(1).to({x:-264.3},0).wait(1).to({x:-489.1},0).wait(1).to({x:-741},0).to({_off:true},1).wait(83));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1148.1,1410.9,253.9,119.5);
// library properties:
lib.properties = {
	width: 1280,
	height: 1024,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/fern.png", id:"fern"},
		{src:"images/Groundsand.png", id:"Groundsand"},
		{src:"images/Groundwork.png", id:"Groundwork"},
		{src:"images/laptop.png", id:"laptop"},
		{src:"images/returnbuttonhover.png", id:"returnbuttonhover"},
		{src:"images/returnbutton.png", id:"returnbutton"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;